import {
  deleteAreaById,
  deleteBankById,
  deleteDepartmentById,
  deleteDesignationById,
  deleteFinancialYearById,
  getAllArea,
  getAllBank,
  getAllCountry,
  getAllDepartment,
  getAllDesignation,
  getAllEmployeeType,
  getAllFinancialYear,
  getAllMetalRate,
  getAllProfile,
  updateAreaStatus,
  updateBankStatus,
  updateDepartmentStatus,
  updateDesignationStatus,
  updateProfileStatus,
  deleteProfileById,
  getAllRetUom,
  updateRetUomStatus,
  deleteRetUomById,
  getAllTax,
  updateTaxStatus,
  deleteTaxById,
  deleteAttributeEntryById,
  getAllAttributeEntry,
  updateAttributeEntryStatus,
  getAllOtherCharges,
  deleteOtherChargesById,
  updateOtherChargesStatus,
  getAllPayDevice,
  deletePayDeviceById,
  updatePayDeviceStatus,
  getAllStockIssueType,
  deleteStockIssueTypeById,
  updateStockIssueTypeStatus,
  getAllSupplier,
  deleteSupplierById,
  updateSupplierStatus,
  getAllFloor,
  updateFloorStatus,
  deleteFloorById,
  getAllCounter,
  updateCounterStatus,
  deleteCounterById,
  getAllRegisteredDevice,
  deleteRegisteredDeviceById,
  updateRegisteredDeviceStatus,
  getAllProfession,
  updateProfessionStatus,
  deleteProfessionById,
  getAllContainer,
  updateContainerStatus,
  deleteContainerById,
  getAllOldMetalItem,
  updateOldMetalItemStatus,
  deleteOldMetalItemById,
  getContainerPdfById,
  getAllOtherWeight,
  updateOtherWeightStatus,
  deleteOtherWeightById,
  getAllCashOpeningBalance,
  updateCashOpeningBalanceStatus,
  deleteCashOpeningBalanceById,
  getAllAccountHead,
  updateAccountHeadStatus,
  deleteAccountHeadById,
  updateServiceStatus,
  getAllService,
  deleteServiceById,
  getAllCustomerProof,
  updateCustomerProofStatus,
  deleteCustomerProofById,
  deleteCountryById,
  getAllState,
  deleteStateById,
  getAllCity,
  deleteCityById,
  getAllBankDeposit,
  deleteBankDepositById,
  getAllRelationType,
  deleteRelationTypeById,
  updateRelationTypeStatus,
  getAllDepositMaster,
  updateDepositMasterStatus,
  deleteDepositMasterById,
  getAllIncentiveSettings,
  deleteIncentiveSettingsById,
  getAllReligionMaster,
  deleteReligionMasterById,
  updateReligionMasterStatus,
  getAllBanner,
  deleteBannerById,
  getAllNotification,
  deleteNotificationById,
  getAllDailyStatus,
  deleteDailyStatusById,
  changeStatusDailyStatus,
  getAllRegion,
  updateRegionStatus,
  deleteRegionById,
} from "../../redux/thunks/retailMaster";
import {
  deleteSchemeAccountById,
  deleteSchemeById,
  deleteSchemeClassById,
  getAllClosedSchemeAccount,
  getAllScheme,
  getAllSchemeAccount,
  getAllSchemeClass,
  schemeAccountCloseRevertById,
  updateSchemeClassStatus,
  updateSchemeStatus,
} from "../../redux/thunks/scheme";
import {
  deleteBranchById,
  deleteCompanyById,
  getAllBranch,
  getAllCompany,
  getAllMenu,
  updateBranchStatus,
  getAllSetting,
  deleteSettingByID,
  deleteMenu,
} from "../../redux/thunks/settings";
import {
  deleteCustomerById,
  getAllCustomer,
  updateCustomerStatus,
} from "../../redux/thunks/customer";
import {
  getAllMetal,
  getAllPurity,
  getAllProduct,
  getAllDesign,
  getAllSubDesign,
  getAllSection,
  deleteSectionByID,
  getAllCategory,
  updateCategoryStatus,
  deleteCategoryById,
  updateProductStatus,
  deleteProductById,
  deleteDesignById,
  updateDesignStatus,
  getAllStone,
  updateStoneStatus,
  deleteStoneById,
  deleteSubDesignById,
  updateSubDesignStatus,
  deletePurityById,
  updatePurityStatus,
  deleteMetalById,
  updateMetalStatus,
  updateSectionStatus,
  getAllCut,
  updateCutStatus,
  deleteCutById,
  getAllColor,
  updateColorStatus,
  deleteColorById,
  getAllShape,
  updateShapeStatus,
  deleteShapeById,
  getAllClarity,
  updateClarityStatus,
  deleteClarityById,
  getAllQuality,
  updateQualityStatus,
  deleteQualityById,
  getAllSize,
  deleteSizeById,
  updateSizeStatus,
  updateRepairDamageMasterStatus,
  deleteRepairDamageMasterById,
  getAllRepairDamageMaster,
  getAllDiamondRateMaster,
  updateDiamondRateMasterStatus,
  deleteDiamondRateMasterById,
  getAllCategoryPurityRate,
} from "../../redux/thunks/catalogMaster";
import {
  getClosedAccountReport,
  getCustomerOutstandingReport,
  getModeWiseCollectionReport,
  getSchemeWiseOpeningReport,
  getUnpaidReport,
  getStockReport,
  getStockInAndOutReport,
  getStockTrasferReport,
  getSalesReport,
  getPurchaseReport,
  getStockAuditReport,
  getStockAuditDetailReport,
  getB2bReport,
  getAdvanceReport,
  getCreditInvoiceReportReport,
  getCreditCollectionReportReport,
  getAdvanceRefundReport,
  getChitAdjReport,
  getAdvanceAdjReport,
  getSalesReturnReport,
  getCreditPendingReport,
  getPettyCashReport,
  getEmployeeSalesReport,
  getCreditIssuePendingReport,
  getPartlySalesReport,
  getSupplierWiseSalesReport,
  getTagWiseProfitReport,
  getCancelBillsReport,
  getDiscountBillsReport,
  getBillWiseTransactionReport,
  getSalesAndSalesReturnGSTReport,
  getPanBillsReport,
  getSalesTargetReport,
  getCreditTobeReport,
  getJewelNotDeliveredReport,
  getMetalProcessReport,
  getOtherMetalStockInAndOutReport,
  getCashBookReport,
  getOtherMetalProfitLossReport,
  getEdaPurchaseReport,
  getEdaSalesReport,
  getAbove2LakhsBillsReport,
  getEmployeeIncentiveReport,
  getSuppliersLedgerReport,
  getWeightRangeWiseSaleReport,
  getPaymentDevicesWiseReport,
  getPurchaseReturnReport,
  getTagDetailsReport,
  getMonthWiseSalesReport,
  getLotReport,
  getStockInwardReport,
  getCustomerJewelNotDeliveredReport,
  getOtherInventoryItemLogReport,
  getOtherInventoryItemPurchaseReport,
  getOtherInventoryItemIssueReport,
  getMonthWisePurchaseEntryReport,
  getVoucherIssueReport,
  getDigiGoldReport,
  getAccountWiseDigiGoldReport,
  getEstimateReport,
  getLotBalanceReport,
  getStockApprovalPendingReport,
  getLiablitySupplierPaymentReport,
  getPurchasePaymentSummaryReport,
  getareawisesalesreport,
} from "../../redux/thunks/reports";
import { getAllPayments } from "../../redux/thunks/payment";
import {
  deleteEmployeeById,
  getAllEmployee,
  updateEmployeeStatus,
} from "../../redux/thunks/employee";
import { estimationList } from "../../redux/thunks/estimation";
import {
  closeLot,
  getLotList,
  getStockTransferList,
  getTagList,
  cancelStockTransfer,
  printLotQRCode,
  getTagIssueReceiptList,
  getLotIssueReceiptList,
  getNonTagInwardList,
  detailStockTransferPrint,
  UpdatelotClose,
} from "../../redux/thunks/inventory";
import {
  deleteOrderById,
  deletePurchaseOrderById,
  getAllCustomerDeposits,
  getAllOrder,
  getAllPurchaseOrder,
  getPurchaseOrderPurchaseSoldDetails,
  getRepairOrderList,
} from "../../redux/thunks/Order";
import {
  getBillingList,
  cancelInvoice,
  getIssueReceiptList,
  cancelIssueReceipt,
  getBankSettlementList,
  getDiscountBillingList,
  getLiablityEntry,
  getLiablityEntryPayment,
  customerSalesLog,
} from "../../redux/thunks/billing";
import {
  getPurchaseDetailsList,
  updatePurchaseEntryStatus,
  cancelPurchaseEntry,
  getPurchaseIssueReciptList,
  cancelPurchaseIssueRecipt,
  getMetalIssueList,
  getPurchaseReturnList,
  cancelPurchaseReturn,
  updatePurchaseReturnStatus,
  getSupplierPaymentList,
} from "../../redux/thunks/purchase";
import { getPocketDetailsList } from "../../redux/thunks/metalProcess";
import {
  cancelOtherInventoryItemIssue,
  cancelOtherInventoryPurchase,
  deleteOtherInventoryCategoryById,
  deleteOtherInventoryItemById,
  deleteOtherInventorySizeById,
  getAllOtherInventoryCategory,
  getAllOtherInventoryItem,
  getAllOtherInventoryItemIssue,
  getAllOtherInventoryPurchase,
  getOtherInventorySize,
  updateOtherInventorySizeStatus,
} from "../../redux/thunks/otherInventory";
import { getAllBuySell } from "../../redux/thunks/mcx";
import {
  deleteCouponById,
  deleteDiscountById,
  deleteGiftVoucherById,
  getAllCoupon,
  getAllDiscount,
  getAllGiftVoucher,
  getAllVoucherIssue,
} from "../../redux/thunks/promotionManagement";

import {
  deleteClientById,
  getAllClient,
  updateClientStatus,
  getAllMasterClients,
  updateMasterClientsById,
  deleteMasterClientsById,
  getAllMasterModule,
  deleteMasterModuleById,
  getAllAdminProductMaster,
  deleteAdminProductMasterById,
} from "../../redux/thunks/adminMaster";
import {
  deleteLoyaltyCustomerById,
  deleteLoyaltyReferralsById,
  deleteLoyaltySettingsById,
  deleteLoyaltyTierById,
  deleteLoyaltyTransactionById,
  getAllLoyaltyCustomer,
  getAllLoyaltyReferrals,
  getAllLoyaltySettings,
  getAllLoyaltyTier,
  getAllLoyaltyTransaction,
} from "../../redux/thunks/loyaltyMaster";
import {
  getAllProject,
  getProjectById,
  createProject,
  updateProjectById,
  deleteProjectById,
  getAllTask,
  deleteTaskById,
  getAllSubTask,
  deleteSubTaskById,
  searchPerformanceInvoice,
  getAllPerformanceInvoice,
  deletePerformanceInvoiceById,
  createPerformanceInvoice,
  updatePerformanceInvoiceById,
  getPerformanceInvoiceById,
  getAllErpAttendance,
  createErpAttendance,
  updateErpAttendanceById,
  deleteErpAttendanceById,
  updateErpAttendanceStatus,
} from "../../redux/thunks/adminProject";

export const matcherData = [
  {
    title: "Relation Type",
    url: "/master/relationtype/list",
    action: getAllRelationType,
    deleteAction: deleteRelationTypeById,
    updateStatusAction: updateRelationTypeStatus,
    sliceName: "relationTypeReducer",
    dataKey: "relationTypeList",
    loaderKey: "isLoading",
    addPageURL: "/master/relationtype/add",
    editPageURL: "/master/relationtype/edit",
  },
  {
    title: "Department",
    url: "/master/department/list",
    action: getAllDepartment,
    deleteAction: deleteDepartmentById,
    updateStatusAction: updateDepartmentStatus,
    sliceName: "departmentReducer",
    dataKey: "departmentList",
    loaderKey: "isLoading",
    addPageURL: "/master/department/add",
    editPageURL: "/master/department/edit",
  },
  {
    title: "Designation",
    url: "/master/designation/list",
    action: getAllDesignation,
    updateStatusAction: updateDesignationStatus,
    deleteAction: deleteDesignationById,
    sliceName: "designationReducer",
    dataKey: "designationList",
    loaderKey: "isLoading",
    addPageURL: "/master/designation/add",
    editPageURL: "/master/designation/edit",
  },
  {
    title: "Menu",
    url: "/settings/menu/list",
    action: getAllMenu,
    deleteAction: deleteMenu,
    sliceName: "menuReducer",
    dataKey: "menuList",
    loaderKey: "isLoading",
    addPageURL: "/settings/menu/add",
    editPageURL: "/settings/menu/edit",
  },
  {
    title: "Area",
    url: "/master/area/list",
    action: getAllArea,
    deleteAction: deleteAreaById,
    updateStatusAction: updateAreaStatus,
    sliceName: "areaReducer",
    dataKey: "areaList",
    loaderKey: "isLoading",
    addPageURL: "/master/area/add",
    editPageURL: "/master/area/edit",
  },
  {
    title: "Bank",
    url: "/master/bank/list",
    action: getAllBank,
    deleteAction: deleteBankById,
    updateStatusAction: updateBankStatus,
    sliceName: "bankReducer",
    dataKey: "bankList",
    loaderKey: "isLoading",
    addPageURL: "/master/bank/add",
    editPageURL: "/master/bank/edit",
  },
  {
    title: "Banner",
    url: "/master/banner/list",
    action: getAllBanner,
    deleteAction: deleteBannerById,
    // updateStatusAction: updateBankStatus,
    sliceName: "bannerReducer",
    dataKey: "bannerList",
    loaderKey: "isLoading",
    addPageURL: "/master/banner/add",
    editPageURL: "/master/banner/edit",
  },
  {
    title: "Daily Status",
    url: "/master/daily_status/list",
    action: getAllDailyStatus,
    deleteAction: deleteDailyStatusById,
    updateStatusAction: changeStatusDailyStatus,
    sliceName: "dailyStatusReducer",
    dataKey: "dailyStatusList",
    loaderKey: "isLoading",
    addPageURL: "/master/daily_status/add",
    editPageURL: "/master/daily_status/edit",
  },
  {
    title: "Notification",
    url: "/master/notification/list",
    action: getAllNotification,
    deleteAction: deleteNotificationById,
    // updateStatusAction: updateBankStatus,
    sliceName: "bannerReducer",
    dataKey: "bannerList",
    loaderKey: "isLoading",
    addPageURL: "/master/notification/add",
    editPageURL: "/master/notification/edit",
  },
  {
    title: "Scheme Classification",
    url: "/schememaster/schemeclassification/list",
    action: getAllSchemeClass,
    deleteAction: deleteSchemeClassById,
    updateStatusAction: updateSchemeClassStatus,
    sliceName: "schemeClassReducer",
    dataKey: "schemeClassList",
    loaderKey: "isLoading",
    addPageURL: "/schememaster/schemeclassification/add",
    editPageURL: "/schememaster/schemeclassification/edit",
  },
  {
    title: "Financial Year",
    url: "/master/financialyear/list",
    action: getAllFinancialYear,
    deleteAction: deleteFinancialYearById,
    // updateStatusAction: updateFinancialYeaStatus,
    sliceName: "financialYearReducer",
    dataKey: "financialYearList",
    loaderKey: "isLoading",
    addPageURL: "/master/financialyear/add",
    // editPageURL: "/master/financialyear/edit",
  },
  {
    title: "Profile",
    url: "/master/profile/list",
    action: getAllProfile,
    sliceName: "profileReducer",
    dataKey: "profileList",
    loaderKey: "isLoading",
    addPageURL: "/master/profile/add",
    editPageURL: "/master/profile/edit",
    updateStatusAction: updateProfileStatus,
    deleteAction: deleteProfileById,
  },
  {
    title: "UOM",
    url: "/master/uom/list",
    action: getAllRetUom,
    sliceName: "uomReducer",
    dataKey: "uomList",
    loaderKey: "isLoading",
    addPageURL: "/master/uom/add",
    editPageURL: "/master/uom/edit",
    updateStatusAction: updateRetUomStatus,
    deleteAction: deleteRetUomById,
  },

  {
    title: "Company",
    url: "/settings/company/list",
    action: getAllCompany,
    deleteAction: deleteCompanyById,
    sliceName: "companyReducer",
    dataKey: "companyList",
    loaderKey: "isLoading",
    addPageURL: "/settings/company/add",
    editPageURL: "/settings/company/edit",
  },
  {
    title: "Scheme",
    url: "/schememaster/scheme/list",
    action: getAllScheme,
    deleteAction: deleteSchemeById,
    updateStatusAction: updateSchemeStatus,
    sliceName: "schemesReducer",
    dataKey: "schemeList",
    loaderKey: "isLoading",
    addPageURL: "/schememaster/scheme/add",
    editPageURL: "/schememaster/scheme/edit",
  },
  {
    title: "Employee",
    url: "/settings/employee/list",
    action: getAllEmployee,
    deleteAction: deleteEmployeeById,
    updateStatusAction: updateEmployeeStatus,
    sliceName: "employeeReducer",
    dataKey: "employeeList",
    loaderKey: "isLoading",
    addPageURL: "/settings/employee/add",
    editPageURL: "/settings/employee/edit",
  },
  {
    title: "Customer",
    url: "/master/customer/list",
    action: getAllCustomer,
    deleteAction: deleteCustomerById,
    updateStatusAction: updateCustomerStatus,
    sliceName: "customerReducer",
    dataKey: "customerList",
    loaderKey: "isLoading",
    addPageURL: "/master/customer/add",
    editPageURL: "/master/customer/edit",
  },
  {
    title: "Scheme Account",
    url: "/schememaster/schemeaccount/list",
    action: getAllSchemeAccount,
    deleteAction: deleteSchemeAccountById,
    sliceName: "schemeAccountReducer",
    dataKey: "schemeAccountList",
    loaderKey: "isLoading",
    is_close_req: true,
    is_history_req: true,
    is_history_editable: true,
    addPageURL: "/schememaster/schemeaccount/add",
    editPageURL: "/schememaster/schemeaccount/edit",
    closePageURL: "/schememaster/schemeaccount/close",
    historyPageURL: "/schememaster/schemeaccount/history",
  },
  {
    title: "Closed Accounts",
    url: "/schememaster/closedschemeaccount/list",
    is_history_req: true,
    is_history_editable: false,
    revertAction: schemeAccountCloseRevertById,
    action: getAllClosedSchemeAccount,
    sliceName: "schemeAccountReducer",
    dataKey: "closedSchemeAccountList",
    loaderKey: "isLoading",
  },
  {
    title: "Payments",
    url: "/payments/schemepayment/list",
    action: getAllPayments,
    sliceName: "paymentMasterReducer",
    // is_history_req : true,
    is_history_editable: true,
    dataKey: "paymentList",
    loaderKey: "isLoading",
    addPageURL: "/payments/schemepayment/add",
    printPageURL: "payment/receipt",
    is_print_req: true,
  },
  {
    title: "Metal Rate",
    url: "/master/metalrate/list",
    action: getAllMetalRate,
    sliceName: "metalRateReducer",
    dataKey: "metalRateList",
    loaderKey: "isLoading",
    addPageURL: "/master/metalrate/add",
    editPageURL: "/master/metalrate/edit",
  },
  {
    title: "Metal",
    url: "/catalogmaster/metal/list",
    action: getAllMetal,
    deleteAction: deleteMetalById,
    updateStatusAction: updateMetalStatus,
    sliceName: "metalReducer",
    dataKey: "metalList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/metal/add",
    editPageURL: "/catalogmaster/metal/edit",
  },
  {
    title: "Purity",
    url: "/catalogmaster/purity/list",
    action: getAllPurity,
    deleteAction: deletePurityById,
    updateStatusAction: updatePurityStatus,
    sliceName: "purityReducer",
    dataKey: "purityList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/purity/add",
    editPageURL: "/catalogmaster/purity/edit",
  },
  {
    title: "Cut",
    url: "/catalogmaster/cut/list",
    action: getAllCut,
    deleteAction: deleteCutById,
    updateStatusAction: updateCutStatus,
    sliceName: "cutReducer",
    dataKey: "cutList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/cut/add",
    editPageURL: "/catalogmaster/cut/edit",
  },

  {
    title: "Color",
    url: "/catalogmaster/color/list",
    action: getAllColor,
    deleteAction: deleteColorById,
    updateStatusAction: updateColorStatus,
    sliceName: "colorReducer",
    dataKey: "colorList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/color/add",
    editPageURL: "/catalogmaster/Color/edit",
  },

  {
    title: "Shape",
    url: "/catalogmaster/shape/list",
    action: getAllShape,
    deleteAction: deleteShapeById,
    updateStatusAction: updateShapeStatus,
    sliceName: "shapeReducer",
    dataKey: "shapeList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/shape/add",
    editPageURL: "/catalogmaster/shape/edit",
  },

  {
    title: "Clarity",
    url: "/catalogmaster/clarity/list",
    action: getAllClarity,
    deleteAction: deleteClarityById,
    updateStatusAction: updateClarityStatus,
    sliceName: "clarityReducer",
    dataKey: "clarityList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/clarity/add",
    editPageURL: "/catalogmaster/clarity/edit",
  },

  {
    title: "Quality",
    url: "/catalogmaster/quality/list",
    action: getAllQuality,
    deleteAction: deleteQualityById,
    updateStatusAction: updateQualityStatus,
    sliceName: "qualityReducer",
    dataKey: "qualityList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/quality/add",
    editPageURL: "/catalogmaster/quality/edit",
  },

  {
    title: "Stone",
    url: "/catalogmaster/stone/list",
    action: getAllStone,
    sliceName: "stoneReducer",
    dataKey: "stoneList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/stone/add",
    editPageURL: "/catalogmaster/stone/edit",
    deleteAction: deleteStoneById,
    updateStatusAction: updateStoneStatus,
  },
  {
    title: "Collection Report",
    url: "/reports/collection_report/list",
    action: getModeWiseCollectionReport,
    sliceName: "reportReducer",
    dataKey: "modeWiseCollectionReportList",
    loaderKey: "isLoading",
    addPageURL: "/reports/collection_report/add",
    editPageURL: "/reports/collection_report/edit",
  },
  {
    title: "Unpaid Report",
    url: "/reports/unpaid_report/list",
    action: getUnpaidReport,
    sliceName: "reportReducer",
    dataKey: "unpaidReportList",
    loaderKey: "isLoading",
    addPageURL: "/reports/unpaid_report/add",
    editPageURL: "/reports/unpaid_report/edit",
  },
  {
    title: "Tag Details",
    url: "/reports/tag_details/list",
    action: getTagDetailsReport,
    sliceName: "reportReducer",
    dataKey: "tagDetailsList",
    loaderKey: "isLoading",
    addPageURL: "#",
    editPageURL: "#",
  },
  {
    title: "Customer Outstanding Report",
    url: "/reports/customer_outstanding_report/list",
    action: getCustomerOutstandingReport,
    sliceName: "reportReducer",
    dataKey: "customerOutstandingReportList",
    loaderKey: "isLoading",
    addPageURL: "/reports/customer_outstanding_report/add",
    editPageURL: "/reports/customer_outstanding_report/edit",
  },
  {
    title: "Scheme Wise Opening Report",
    url: "/reports/scheme_wise_opening/list",
    action: getSchemeWiseOpeningReport,
    sliceName: "reportReducer",
    dataKey: "schemeWiseOpeningReportList",
    loaderKey: "isLoading",
    addPageURL: "/reports/scheme_wise_opening/add",
    editPageURL: "/reports/scheme_wise_opening/edit",
  },
  {
    title: "Closed Account Report",
    url: "/reports/closed_account_report/list",
    action: getClosedAccountReport,
    sliceName: "reportReducer",
    dataKey: "closedAccountReportList",
    loaderKey: "isLoading",
    addPageURL: "/reports/closed_account_report/add",
    editPageURL: "/reports/closed_account_report/edit",
  },
  {
    title: "Branch",
    url: "/master/branch/list",
    action: getAllBranch,
    deleteAction: deleteBranchById,
    updateStatusAction: updateBranchStatus,
    sliceName: "branchReducer",
    dataKey: "branchList",
    loaderKey: "isLoading",
    addPageURL: "/master/branch/add",
    editPageURL: "/master/branch/edit",
  },
  {
    title: "Employee Type",
    url: "/master/employeetype/list",
    action: getAllEmployeeType,
    sliceName: "employeeTypeReducer",
    dataKey: "employeeTypeList",
    loaderKey: "isLoading",
    addPageURL: "/master/employeetype/add",
    editPageURL: "/master/employeetype/edit",
  },
  {
    title: "Country",
    url: "/master/country/list",
    action: getAllCountry,
    sliceName: "countryReducer",
    dataKey: "countryList",
    loaderKey: "isLoading",
    addPageURL: "/master/country/add",
    editPageURL: "/master/country/edit",
    deleteAction: deleteCountryById,
  },
  {
    title: "State",
    url: "/master/state/list",
    action: getAllState,
    sliceName: "stateReducer",
    dataKey: "stateList",
    loaderKey: "isLoading",
    addPageURL: "/master/state/add",
    editPageURL: "/master/state/edit",
    deleteAction: deleteStateById,
  },
  {
    title: "City",
    url: "/master/city/list",
    action: getAllCity,
    sliceName: "cityReducer",
    dataKey: "cityList",
    loaderKey: "isLoading",
    addPageURL: "/master/city/add",
    editPageURL: "/master/city/edit",
    deleteAction: deleteCityById,
  },
  {
    title: "Product",
    url: "/catalogmaster/product/list",
    action: getAllProduct,
    deleteAction: deleteProductById,
    updateStatusAction: updateProductStatus,
    sliceName: "productReducer",
    dataKey: "productList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/product/add",
    editPageURL: "/catalogmaster/product/edit",
  },
  {
    title: "Design",
    url: "/catalogmaster/design/list",
    action: getAllDesign,
    deleteAction: deleteDesignById,
    updateStatusAction: updateDesignStatus,
    sliceName: "designReducer",
    dataKey: "activeDesignList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/design/add",
    editPageURL: "/catalogmaster/design/edit",
  },
  {
    title: "Sub Design",
    url: "/catalogmaster/sub_design/list",
    action: getAllSubDesign,
    deleteAction: deleteSubDesignById,
    updateStatusAction: updateSubDesignStatus,
    sliceName: "subDesignReducer",
    dataKey: "activeSubDesignList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/sub_design/add",
    editPageURL: "/catalogmaster/sub_design/edit",
  },
  {
    title: "Section",
    url: "/catalogmaster/section/list",
    action: getAllSection,
    updateStatusAction: updateSectionStatus,
    sliceName: "sectionReducer",
    dataKey: "sectionList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/section/add",
    editPageURL: "/catalogmaster/section/edit",
    deleteAction: deleteSectionByID,
  },
  {
    title: "Category",
    url: "/catalogmaster/category/list",
    action: getAllCategory,
    updateStatusAction: updateCategoryStatus,
    deleteAction: deleteCategoryById,
    sliceName: "categoryReducer",
    dataKey: "categoryList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/category/add",
    editPageURL: "/catalogmaster/category/edit",
  },
  {
    title: "Lot",
    url: "/inventory/lot/list",
    action: getLotList,
    sliceName: "lotReducer",
    dataKey: "lotList",
    loaderKey: "isLoading",
    addPageURL: "/inventory/lot/add",
    editPageURL: "/inventory/lot/edit",
    is_print_req: true,
    is_qrprint_req: true,
    qrPrintType : "lot",
    qrPrintAction: printLotQRCode,
    printPageURL: "inventory/lot/print",
    updateStatusAction: closeLot,
  },
  {
    title: "Tag",
    url: "/inventory/tag/list",
    action: getTagList,
    sliceName: "tagReducer",
    dataKey: "tagList",
    loaderKey: "isLoading",
    addPageURL: "/inventory/tag/add",
    editPageURL: "",
  },
  {
    title: "Taxmaster",
    url: "/master/tax/list",
    action: getAllTax,
    sliceName: "taxmasterReducer",
    dataKey: "taxMasterList",
    loaderKey: "isLoading",
    addPageURL: "/master/tax/add",
    editPageURL: "/master/tax/edit",
    updateStatusAction: updateTaxStatus,
    deleteAction: deleteTaxById,
  },
  {
    title: "Size",
    url: "/catalogmaster/size/list",
    action: getAllSize,
    // updateStatusAction: updateSectionStatus,
    sliceName: "sizeReducer",
    dataKey: "sizeList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/size/add",
    editPageURL: "/catalogmaster/size/edit",
    // deleteAction: deleteSectionByID,
  },

  {
    title: "Settings",
    url: "/settings/list",
    action: getAllSetting,
    sliceName: "settingReducer",
    dataKey: "settingList",
    loaderKey: "isLoading",
    addPageURL: "/settings/add",
    editPageURL: "/settings/edit",
    deleteAction: deleteSettingByID,
  },
  {
    title: "Taxmaster",
    url: "/master/tax/list",
    action: getAllTax,
    sliceName: "taxmasterReducer",
    dataKey: "taxMasterList",
    loaderKey: "isLoading",
    addPageURL: "/master/tax/add",
    editPageURL: "/master/tax/edit",
    updateStatusAction: updateTaxStatus,
    deleteAction: deleteTaxById,
  },
  {
    title: "Size",
    url: "/catalogmaster/size/list",
    action: getAllSize,
    updateStatusAction: updateSizeStatus,
    sliceName: "sizeReducer",
    dataKey: "sizeList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/size/add",
    editPageURL: "/catalogmaster/size/edit",
    deleteAction: deleteSizeById,
  },
  {
    title: "Estimation",
    url: "/estimation/list",
    action: estimationList,
    updateStatusAction: "",
    sliceName: "estReducer",
    dataKey: "estimationList",
    loaderKey: "isLoading",
    addPageURL: "/estimation/add",
    editPageURL: "/estimation/edit",
    deleteAction: "",
    printType: "page",
    printPageURL: "estimation/print",
    is_print_req: true,
  },
  {
    title: "Attribute",
    url: "/master/attributeentry/list",
    action: getAllAttributeEntry,
    deleteAction: deleteAttributeEntryById,
    updateStatusAction: updateAttributeEntryStatus,
    sliceName: "attributeEntryReducer",
    dataKey: "attributeEntryList",
    loaderKey: "isLoading",
    addPageURL: "/master/attributeentry/add",
    editPageURL: "/master/attributeentry/edit",
  },
  {
    title: "Other Charges",
    url: "/master/othercharges/list",
    action: getAllOtherCharges,
    deleteAction: deleteOtherChargesById,
    updateStatusAction: updateOtherChargesStatus,
    sliceName: "otherChargesReducer",
    dataKey: "otherChargesList",
    loaderKey: "isLoading",
    addPageURL: "/master/othercharges/add",
    editPageURL: "/master/othercharges/edit",
  },
  {
    title: "Order",
    url: "/order/createorder/list",
    action: getAllOrder,
    deleteAction: deleteOrderById,
    sliceName: "orderReducer",
    dataKey: "orderList",
    loaderKey: "isLoading",
    addPageURL: "/order/createorder/add",
    editPageURL: "/order/createorder/edit",
    printPageURL: "orders/order/print",
    is_print_req: true,
    printType: "page",
  },
  {
    title: "Purchase Order",
    url: "/order/purchaseorder/list",
    action: getAllPurchaseOrder,
    deleteAction: deletePurchaseOrderById,
    sliceName: "orderReducer",
    dataKey: "purchaseOrderList",
    loaderKey: "isLoading",
    addPageURL: "/order/purchaseorder/add",
    editPageURL: "/order/purchaseorder/edit",
    printPageURL: "orders/purchase_order/print",
    printType: "page",
    is_print_req: true,
  },
  {
    title: "Purchase Order",
    url: "/order/purchaseorder/sold_purchase_report",
    action: getPurchaseOrderPurchaseSoldDetails,
    // deleteAction: deletePurchaseOrderById,
    sliceName: "orderReducer",
    dataKey: "purchaseOrderPurchaseSoldDetails",
    loaderKey: "isLoading",
  },
  {
    title: "Diamond Rate",
    url: "/catalogmaster/diamondratemaster/list",
    action: getAllDiamondRateMaster,
    deleteAction: deleteDiamondRateMasterById,
    updateStatusAction: updateDiamondRateMasterStatus,
    sliceName: "diamondRateMasterReducer",
    dataKey: "diamondRateMasterList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/diamondratemaster/add",
    editPageURL: "/catalogmaster/diamondratemaster/edit",
  },
  {
    title: "pay Device",
    url: "/master/paydevice/list",
    action: getAllPayDevice,
    deleteAction: deletePayDeviceById,
    updateStatusAction: updatePayDeviceStatus,
    sliceName: "payDeviceReducer",
    dataKey: "payDeviceList",
    loaderKey: "isLoading",
    addPageURL: "/master/paydevice/add",
    editPageURL: "/master/paydevice/edit",
  },
  {
    title: "Stock Issue Type",
    url: "/master/stockissuetype/list",
    action: getAllStockIssueType,
    deleteAction: deleteStockIssueTypeById,
    updateStatusAction: updateStockIssueTypeStatus,
    sliceName: "stockIssueTypeReducer",
    dataKey: "stockIssueTypeList",
    loaderKey: "isLoading",
    addPageURL: "/master/stockissuetype/add",
    editPageURL: "/master/stockissuetype/edit",
  },
  {
    title: "Stock Transfer",
    url: "/inventory/stock_transfer/list",
    action: getStockTransferList,
    cancelAction: cancelStockTransfer,
    sliceName: "stockTransferReducer",
    dataKey: "stockTransferList",
    loaderKey: "isLoading",
    addPageURL: "/inventory/stock_transfer/add",
    editPageURL: "/inventory/stock_transfer/edit",
    is_print_req: true,
    is_detail_print_req: true,
    printPageURL: "stock_transfer/print",
    detailPrintPageURL: "stock_transfer/print",
    printPdfAction: detailStockTransferPrint,
    printType: "page",
  },
  {
    title: "Billing",
    url: "/billing/list",
    action: getBillingList,
    cancelAction: cancelInvoice,
    sliceName: "billingReducer",
    dataKey: "invoiceList",
    loaderKey: "isLoading",
    addPageURL: "/billing/add",
    editPageURL: "/billing/edit",
    is_print_req: true,
    printType: "page",
    printPageURL: "billing/print",
    is_detail_print_req: true,
    detailPrintPageURL: "billing/thermal_print",
  },
  {
    title: "Issue Receipt",
    url: "/receipt/list",
    action: getIssueReceiptList,
    cancelAction: cancelIssueReceipt,
    sliceName: "receiptReducer",
    dataKey: "receiptList",
    loaderKey: "isLoading",
    addPageURL: "/receipt/add",
    editPageURL: "/receipt/edit",
    is_print_req: true,
    printType: "page",
    printPageURL: "billing/issue_receipt/print",
  },
  {
    title: "Available Stock Report",
    url: "/reports/stock_report/list",
    action: getStockReport,
    sliceName: "reportReducer",
    dataKey: "stockReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Stock Transfer Report",
    url: "/reports/stock_transfer_report/list",
    action: getStockTrasferReport,
    sliceName: "reportReducer",
    dataKey: "stockTransferReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Karigar",
    url: "/master/karigar/list",
    action: getAllSupplier,
    deleteAction: deleteSupplierById,
    updateStatusAction: updateSupplierStatus,
    sliceName: "karigarReducer",
    dataKey: "karigarList",
    loaderKey: "isLoading",
    addPageURL: "/master/karigar/add",
    editPageURL: "/master/karigar/edit",
  },
  {
    title: "Sales Report",
    url: "/reports/sales_report/list",
    action: getSalesReport,
    sliceName: "reportReducer",
    dataKey: "salesReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Purchase Report",
    url: "/reports/purchase_report/list",
    action: getPurchaseReport,
    sliceName: "reportReducer",
    dataKey: "purchaseReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Stock Audit Report",
    url: "/reports/stock_audit_report/list",
    action: getStockAuditReport,
    sliceName: "reportReducer",
    dataKey: "StockAuditReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Stock Audit Detail Report",
    url: "/reports/stock_audit_detail_report/list",
    action: getStockAuditDetailReport,
    sliceName: "reportReducer",
    dataKey: "StockAuditDetailsReportList",
    loaderKey: "isLoading",
  },
  {
    title: "B2B Sales Report",
    url: "/reports/b2b_report/list",
    action: getB2bReport,
    sliceName: "reportReducer",
    dataKey: "B2bReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Advance Report",
    url: "/reports/advance_report/list",
    action: getAdvanceReport,
    sliceName: "reportReducer",
    dataKey: "advanceReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Credit Invoice Report",
    url: "/reports/credit_invoice_report/list",
    action: getCreditInvoiceReportReport,
    sliceName: "reportReducer",
    dataKey: "creditInvoiceReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Credit Collection Report",
    url: "/reports/credit_collection_report/list",
    action: getCreditCollectionReportReport,
    sliceName: "reportReducer",
    dataKey: "creditCollectionReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Mode Wise Collection Report",
    url: "/reports/mode_wise_collection_report/list",
    action: getModeWiseCollectionReport,
    sliceName: "reportReducer",
    dataKey: "modeWiseCollectionReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Advance Adjusted Report",
    url: "/reports/advance_adjusted_report/list",
    action: getAdvanceAdjReport,
    sliceName: "reportReducer",
    dataKey: "advAdjReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Advance Refund Report",
    url: "/reports/advance_refund_report/list",
    action: getAdvanceRefundReport,
    sliceName: "reportReducer",
    dataKey: "advRefundReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Chit Adjusted Report",
    url: "/reports/chit_adjusted_report/list",
    action: getChitAdjReport,
    sliceName: "reportReducer",
    dataKey: "chitAdjReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Sales Return Report",
    url: "/reports/sales_return_report/list",
    action: getSalesReturnReport,
    sliceName: "reportReducer",
    dataKey: "salesReturnReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Credit Pending Report",
    url: "/reports/credit_pending_report/list",
    action: getCreditPendingReport,
    sliceName: "reportReducer",
    dataKey: "creditPendingReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Credit Issued Pending Report",
    url: "/reports/credit_issue_pending_report/list",
    action: getCreditIssuePendingReport,
    sliceName: "reportReducer",
    dataKey: "creditIssuePendingReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Petty Cash Report",
    url: "/reports/petty_cash_report/list",
    action: getPettyCashReport,
    sliceName: "reportReducer",
    dataKey: "pettyCashReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Employee Sales Report",
    url: "/reports/emp_sales_report/list",
    action: getEmployeeSalesReport,
    sliceName: "reportReducer",
    dataKey: "employeeSalesReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Partly Sales Report",
    url: "/reports/partly_sales_report/list",
    action: getPartlySalesReport,
    sliceName: "reportReducer",
    dataKey: "partlySalesReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Supplier Sales Report",
    url: "/reports/supplier_sales_report/list",
    action: getSupplierWiseSalesReport,
    sliceName: "reportReducer",
    dataKey: "supplierSalesReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Tag Wise Profit Report",
    url: "/reports/tag_wise_profit_report/list",
    action: getTagWiseProfitReport,
    sliceName: "reportReducer",
    dataKey: "tagWiseSalesProfitReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Cancel Bill Report",
    url: "/reports/cancel_bill_report/list",
    action: getCancelBillsReport,
    sliceName: "reportReducer",
    dataKey: "cancelBillReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Discount Bill Report",
    url: "/reports/discount_bill_report/list",
    action: getDiscountBillsReport,
    sliceName: "reportReducer",
    dataKey: "discountBillReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Gift Voucher Issue Report",
    url: "/reports/gift_voucher_issue_report/list",
    action: getVoucherIssueReport,
    sliceName: "reportReducer",
    dataKey: "voucherIssueReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Digi Gold Payment Report",
    url: "/reports/digi_gold_reports/list",
    action: getDigiGoldReport,
    is_history_req: true,
    is_history_editable: false,
    sliceName: "reportReducer",
    dataKey: "digiGoldReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Digi Gold Account Summary",
    url: "/reports/account_wise_digi_gold_reports/list",
    action: getAccountWiseDigiGoldReport,
    is_history_req: true,
    is_history_editable: false,
    sliceName: "reportReducer",
    dataKey: "accountWiseDigiGoldReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Pan Bill Report",
    url: "/reports/pan_bill_report/list",
    action: getPanBillsReport,
    sliceName: "reportReducer",
    dataKey: "panBillsReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Bill-Wise Transaction Report",
    url: "/reports/billwise_transaction_report/list",
    action: getBillWiseTransactionReport,
    sliceName: "reportReducer",
    dataKey: "billWiseTransationReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Sales and Sales Return GST Abstract Report",
    url: "/reports/sales_and_return_report/list",
    action: getSalesAndSalesReturnGSTReport,
    sliceName: "reportReducer",
    dataKey: "salesAndSalesReturnReportList",
    loaderKey: "isLoading",
  },
  // {
  //   title: "Weight Range",
  //   url: "/master/weightrange/list",
  //   action: getAllWeightRange,
  //   deleteAction: deleteWeightRangeById,
  //   updateStatusAction: updateWeightRangeStatus,
  //   sliceName: "weightRangeReducer",
  //   dataKey: "weightRangeList",
  //   loaderKey: "isLoading",
  //   addPageURL: "/master/weightrange/add",
  //   editPageURL: "/master/weightrange/edit",
  // },

  {
    title: "Purchase Entry",
    url: "/purchase/purchase_entry/list",
    action: getPurchaseDetailsList,
    sliceName: "purchaseReducer",
    dataKey: "purchaseListDetails",
    loaderKey: "isLoading",
    addPageURL: "/purchase/purchase_entry/add",
    editPageURL: "/purchase/purchase_entry/edit",
    updateStatusAction: updatePurchaseEntryStatus,
    cancelAction: cancelPurchaseEntry,
    printType: "page",
    printPageURL: "purchase/purchase_entry/print",
    is_print_req: true,
  },
  {
    title: "Purchase Return",
    url: "/purchase/purchase_return/list",
    action: getPurchaseReturnList,
    sliceName: "purchaseReturnReducer",
    dataKey: "purchaseReturnDetailsList",
    loaderKey: "isLoading",
    addPageURL: "/purchase/purchase_return/add",
    editPageURL: "/purchase/purchase_return/edit",
    is_print_req: true,
    printPageURL: "purchase/purchase_return/print",
    updateStatusAction: updatePurchaseReturnStatus,
    cancelAction: cancelPurchaseReturn,
  },
  {
    title: "QC/HM Issue Receipt",
    url: "/purchase/qu_issue_receipt/list",
    action: getPurchaseIssueReciptList,
    sliceName: "purchaseIssueReceiptReducer",
    dataKey: "purchaseIssueReceiptList",
    loaderKey: "isLoading",
    addPageURL: "/purchase/qu_issue_receipt/add",
    cancelAction: cancelPurchaseIssueRecipt,
    printType: "page",
    is_print_req: true,
    printPageURL: "purchase/qu_issue_receipt/print",
  },
  {
    title: "Floor",
    url: "/master/floor/list",
    action: getAllFloor,
    sliceName: "floorReducer",
    dataKey: "floorList",
    loaderKey: "isLoading",
    addPageURL: "/master/floor/add",
    editPageURL: "/master/floor/edit",
    updateStatusAction: updateFloorStatus,
    deleteAction: deleteFloorById,
  },
  {
    title: "Pocket Entry",
    url: "/oldmetal_process/pocket/list",
    action: getPocketDetailsList,
    sliceName: "metalProcessReducer",
    dataKey: "pocketDetailsList",
    loaderKey: "isLoading",
    addPageURL: "/oldmetal_process/pocket/add",
  },
  {
    title: "Counter",
    url: "/master/counter/list",
    action: getAllCounter,
    sliceName: "counterReducer",
    dataKey: "counterList",
    loaderKey: "isLoading",
    addPageURL: "/master/counter/add",
    editPageURL: "/master/counter/edit",
    updateStatusAction: updateCounterStatus,
    deleteAction: deleteCounterById,
  },
  {
    title: "Registered Device",
    url: "/master/registered_devices/list",
    action: getAllRegisteredDevice,
    sliceName: "registeredDeviceReducer",
    dataKey: "registeredDeviceList",
    loaderKey: "isLoading",
    addPageURL: "/master/registered_devices/add",
    editPageURL: "/master/registered_devices/edit",
    updateStatusAction: updateRegisteredDeviceStatus,
    deleteAction: deleteRegisteredDeviceById,
  },
  // {
  //   title: "Section Wise Sales",
  //   url: "/master/section_wise_sales/list",
  //   action: getAllSectionWiseSales,
  //   sliceName: "sectionWiseSalesReducer",
  //   dataKey: "sectionWiseSalesList",
  //   loaderKey: "isLoading",
  //   addPageURL: "/master/section_wise_sales/add",
  //   editPageURL: "/master/section_wise_sales/edit",
  //   updateStatusAction: updateSectionWiseSalesStatus,
  //   deleteAction: deleteSectionWiseSalesById,
  // },
  {
    title: "Profession",
    url: "/master/profession/list",
    action: getAllProfession,
    sliceName: "professionReducer",
    dataKey: "professionList",
    loaderKey: "isLoading",
    addPageURL: "/master/profession/add",
    editPageURL: "/master/profession/edit",
    updateStatusAction: updateProfessionStatus,
    deleteAction: deleteProfessionById,
  },

  {
    title: "Region",
    url: "/master/region/list",
    action: getAllRegion,
    sliceName: "regionReducer",
    dataKey: "regionList",
    loaderKey: "isLoading",
    addPageURL: "/master/region/add",
    editPageURL: "/master/region/edit",
    updateStatusAction: updateRegionStatus,
    deleteAction: deleteRegionById,
  },


  {
    title: "Bank Settlement",
    url: "/banksettlement/list",
    action: getBankSettlementList,
    sliceName: "bankSettlementReducer",
    dataKey: "bankSettlementListingData",
    loaderKey: "isLoading",
    addPageURL: "/banksettlement/add",
  },
  {
    title: "Sales Target Report",
    url: "/reports/sales_target/list",
    action: getSalesTargetReport,
    sliceName: "reportReducer",
    dataKey: "salesTargetReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Credit Tobe Delivered Report",
    url: "/reports/credit_tobe_delivered/list",
    action: getCreditTobeReport,
    sliceName: "reportReducer",
    dataKey: "creditTobeReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Metal Process Report",
    url: "/reports/metal_process/list",
    action: getMetalProcessReport,
    sliceName: "reportReducer",
    dataKey: "metalProcessReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Container",
    url: "/master/container/list",
    action: getAllContainer,
    sliceName: "containerReducer",
    dataKey: "containerList",
    loaderKey: "isLoading",
    addPageURL: "/master/container/add",
    editPageURL: "/master/container/edit",
    updateStatusAction: updateContainerStatus,
    deleteAction: deleteContainerById,
    printPageURL: undefined,
    printPdfAction: getContainerPdfById,
    is_print_req: true,
  },
  {
    title: "Old Metal Item",
    url: "/master/oldmetaltype/list",
    action: getAllOldMetalItem,
    sliceName: "oldMetalItemReducer",
    dataKey: "oldMetalItemList",
    loaderKey: "isLoading",
    addPageURL: "/master/oldmetaltype/add",
    editPageURL: "/master/oldmetaltype/edit",
    updateStatusAction: updateOldMetalItemStatus,
    deleteAction: deleteOldMetalItemById,
  },
  {
    title: "Purchase Metal Stock In And Out Report",
    url: "/reports/metal_stock_in_and_out/list",
    action: getOtherMetalStockInAndOutReport,
    sliceName: "reportReducer",
    dataKey: "otherMetalStockInAndOutReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Jewel Not Delivered Report",
    url: "/reports/jewel_not_delivered/list",
    action: getJewelNotDeliveredReport,
    sliceName: "reportReducer",
    dataKey: "jewelNotDeliveredReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Other Weight",
    url: "/master/otherweight/list",
    action: getAllOtherWeight,
    sliceName: "otherWeightReducer",
    dataKey: "otherWeightList",
    loaderKey: "isLoading",
    addPageURL: "/master/otherweight/add",
    editPageURL: "/master/otherweight/edit",
    updateStatusAction: updateOtherWeightStatus,
    deleteAction: deleteOtherWeightById,
  },
  {
    title: "Cash Opening Balance",
    url: "/master/cashopeningbalance/list",
    action: getAllCashOpeningBalance,
    sliceName: "cashOpeningBalanceReducer",
    dataKey: "cashOpeningBalanceList",
    loaderKey: "isLoading",
    addPageURL: "/master/cashopeningbalance/add",
    editPageURL: "/master/cashopeningbalance/edit",
    updateStatusAction: updateCashOpeningBalanceStatus,
    deleteAction: deleteCashOpeningBalanceById,
  },
  {
    title: "Damage Master",
    url: "/catalogmaster/damage_master/list",
    action: getAllRepairDamageMaster,
    deleteAction: deleteRepairDamageMasterById,
    updateStatusAction: updateRepairDamageMasterStatus,
    sliceName: "repairDamageMasterReducer",
    dataKey: "repairDamageMasterList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/damage_master/add",
    editPageURL: "/catalogmaster/damage_master/edit",
  },
  {
    title: "Account Head",
    url: "/master/accounthead/list",
    action: getAllAccountHead,
    sliceName: "accountHeadReducer",
    dataKey: "accountHeadList",
    loaderKey: "isLoading",
    addPageURL: "/master/accounthead/add",
    editPageURL: "/master/accounthead/edit",
    updateStatusAction: updateAccountHeadStatus,
    deleteAction: deleteAccountHeadById,
  },
  {
    title: "Repair Order",
    url: "/order/repair_order/list",
    action: getRepairOrderList,
    deleteAction: deleteOrderById,
    sliceName: "orderReducer",
    dataKey: "repairOrderAllList",
    loaderKey: "isLoading",
    addPageURL: "/order/repair_order/add",
    editPageURL: "/order/repair_order/edit",
    printPageURL: "orders/repairorder/print",
    printType: "page",
    is_print_req: true,
  },
  {
    title: "Metal Issue",
    url: "/purchase/metal_issue/list",
    action: getMetalIssueList,
    sliceName: "purchaseReducer",
    dataKey: "metalIssueList",
    loaderKey: "isLoading",
    addPageURL: "/purchase/metal_issue/add",
  },
  {
    title: "Cash Book Report",
    url: "/reports/cash_book/list",
    action: getCashBookReport,
    sliceName: "reportReducer",
    dataKey: "cashBookList",
    loaderKey: "isLoading",
  },
  {
    title: "Supplier ledger Report",
    url: "/reports/supplier_ledger/list",
    action: getCashBookReport,
    sliceName: "reportReducer",
    dataKey: "cashBookList",
    loaderKey: "isLoading",
  },
  {
    title: "Service",
    url: "/master/service/list",
    action: getAllService,
    sliceName: "serviceReducer",
    dataKey: "serviceList",
    loaderKey: "isLoading",
    addPageURL: "/master/service/add",
    editPageURL: "/master/service/edit",
    updateStatusAction: updateServiceStatus,
    deleteAction: deleteServiceById,
  },
  {
    title: "Discount Billing",
    url: "/discount_billing/list",
    action: getDiscountBillingList,
    cancelAction: cancelInvoice,
    sliceName: "billingReducer",
    dataKey: "invoiceDiscountList",
    loaderKey: "isLoading",
    addPageURL: "/billing/add",
    editPageURL: "/billing/edit",
    is_print_req: true,
    printPageURL: "billing/discount_print",
  },
  {
    title: "Customer Proof",
    url: "/master/customerproof/list",
    action: getAllCustomerProof,
    sliceName: "customerProofReducer",
    dataKey: "customerProofList",
    loaderKey: "isLoading",
    addPageURL: "/master/customerproof/add",
    editPageURL: "/master/customerproof/edit",
    updateStatusAction: updateCustomerProofStatus,
    deleteAction: deleteCustomerProofById,
  },

  {
    title: "Sales Report",
    url: "/reports/sale_report/list",
    action: getEdaSalesReport,
    sliceName: "reportReducer",
    dataKey: "edaSaleList",
    loaderKey: "isLoading",
  },

  {
    title: "Purchase Report",
    url: "/reports/purchase_reports/list",
    action: getEdaPurchaseReport,
    sliceName: "reportReducer",
    dataKey: "edaPurchaseList",
    loaderKey: "isLoading",
  },
  {
    title: "Purchase Return Report",
    url: "/reports/purchase_return_reports/list",
    action: getPurchaseReturnReport,
    sliceName: "reportReducer",
    dataKey: "purchaseReturnList",
    loaderKey: "isLoading",
  },

  {
    title: "Metal Process Profit Loss Report",
    url: "/reports/metal_process_profit_loss/list",
    action: getOtherMetalProfitLossReport,
    sliceName: "reportReducer",
    dataKey: "otherMetalProfitLossList",
    loaderKey: "isLoading",
  },
  {
    title: "Bank Deposit",
    url: "/master/bank_deposit/list",
    action: getAllBankDeposit,
    deleteAction: deleteBankDepositById,
    sliceName: "bankDepositReducer",
    dataKey: "bankDepositList",
    loaderKey: "isLoading",
    addPageURL: "/master/bank_deposit/add",
    editPageURL: "/master/bank_deposit/edit",
  },
  {
    title: "Deposit Master",
    url: "/master/depositmaster/list",
    action: getAllDepositMaster,
    sliceName: "depositMasterReducer",
    dataKey: "depositMasterList",
    loaderKey: "isLoading",
    addPageURL: "/master/depositmaster/add",
    editPageURL: "/master/depositmaster/edit",
    updateStatusAction: updateDepositMasterStatus,
    deleteAction: deleteDepositMasterById,
  },
  {
    title: "Customer Deposit",
    url: "/master/customer_deposit/list",
    action: getAllCustomerDeposits,
    sliceName: "customerDepositReducer",
    dataKey: "customerDepositList",
    loaderKey: "isLoading",
    addPageURL: "/master/customer_deposit/add",
    editPageURL: "/master/customer_deposit/edit",
    // updateStatusAction: updateDepositMasterStatus,
    // deleteAction: deleteDepositMasterById,
  },
  {
    title: "Above 2Lakhs Report",
    url: "/reports/above_2L_report/list",
    action: getAbove2LakhsBillsReport,
    sliceName: "reportReducer",
    dataKey: "above2lakhsBillList",
    loaderKey: "isLoading",
  },
  {
    title: "Incentive Master",
    url: "/incentive/master/list",
    action: getAllIncentiveSettings,
    sliceName: "incentiveSettingsReducer",
    dataKey: "incentiveSettingsList",
    loaderKey: "isLoading",
    addPageURL: "/incentive/master/add",
    editPageURL: "/incentive/master/edit",
    deleteAction: deleteIncentiveSettingsById,
  },
  {
    title: "Employee Incentive Report",
    url: "/reports/employee_incentive/list",
    action: getEmployeeIncentiveReport,
    sliceName: "reportReducer",
    dataKey: "incentiveReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Religion",
    url: "/master/religion/list",
    action: getAllReligionMaster,
    deleteAction: deleteReligionMasterById,
    updateStatusAction: updateReligionMasterStatus,
    sliceName: "religionMasterReducer",
    dataKey: "religionMasterList",
    loaderKey: "isLoading",
    addPageURL: "/master/religion/add",
    editPageURL: "/master/religion/edit",
  },
  {
    title: "Category Purity Rate",
    url: "/catalogmaster/category_purity_rate/list",
    action: getAllCategoryPurityRate,
    // deleteAction: deleteReligionMasterById,
    // updateStatusAction: updateReligionMasterStatus,
    sliceName: "categoryPurityRateReducer",
    dataKey: "allCategoryPurityRateList",
    loaderKey: "isLoading",
    addPageURL: "/catalogmaster/category_purity_rate/add",
    // editPageURL: "/master/religion/edit",
  },
  {
    title: "Supplier Ledger Report",
    url: "/reports/suppliers_ledger/list",
    action: getSuppliersLedgerReport,
    sliceName: "reportReducer",
    dataKey: "suppliersLedgerReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Weight Range Based Sales Report",
    url: "/reports/weigt_range_sales_report/list",
    action: getWeightRangeWiseSaleReport,
    sliceName: "reportReducer",
    dataKey: "weightRangeSalesReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Payment Device Report",
    url: "/reports/payment_device_report/list",
    action: getPaymentDevicesWiseReport,
    sliceName: "reportReducer",
    dataKey: "paymentDevicesWiseReport",
    loaderKey: "isLoading",
  },
  {
    title: "Stock In And Out Report",
    url: "/reports/stock_in_and_out/list",
    action: getStockInAndOutReport,
    sliceName: "reportReducer",
    dataKey: "stockInAndOutReportList",
    loaderKey: "isLoading",
    disablePagination: true,
  },
  {
    title: "Month Wise Sales Report",
    url: "/reports/month_wise_sales/list",
    action: getMonthWiseSalesReport,
    sliceName: "reportReducer",
    dataKey: "monthWiseSalesReport",
    loaderKey: "isLoading",
  },
  {
    title: "Month Wise Purchase Entry Report",
    url: "/reports/month_wise_purchase_entry/list",
    action: getMonthWisePurchaseEntryReport,
    sliceName: "reportReducer",
    dataKey: "monthWisePurchaseEntryReport",
    loaderKey: "isLoading",
  },
  {
    title: "Lot Report",
    url: "/reports/lot_report/list",
    action: getLotReport,
    sliceName: "reportReducer",
    dataKey: "lotReport",
    loaderKey: "isLoading",
    updateStatusAction: closeLot,
  },
  {
    title: "Stock Inward Report",
    url: "/reports/stock_inward_report/list",
    action: getStockInwardReport,
    sliceName: "reportReducer",
    dataKey: "stockInwardReport",
    loaderKey: "isLoading",
  },
  {
    title: "Customer Jewel Not Delivered Report",
    url: "/reports/customer_jewel_not_delivered/list",
    action: getCustomerJewelNotDeliveredReport,
    sliceName: "reportReducer",
    dataKey: "customerJewelNotDeliveredReportList",

    loaderKey: "isLoading",
  },
  {
    title: "Other Inventory Item Log Report",
    url: "/reports/other_inventory_item_log/list",
    action: getOtherInventoryItemLogReport,
    sliceName: "reportReducer",
    dataKey: "otherInventoryItemLogReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Estimation Report",
    url: "/reports/estimate_report/list",
    action: getEstimateReport,
    sliceName: "reportReducer",
    dataKey: "estimateReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Other Inventory Item Purchase Report",
    url: "/reports/other_inventory_item_purchase/list",
    action: getOtherInventoryItemPurchaseReport,
    sliceName: "reportReducer",
    dataKey: "otherInventoryItemPurchaseReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Other Inventory Item Issue Report",
    url: "/reports/other_inventory_item_issue/list",
    action: getOtherInventoryItemIssueReport,
    sliceName: "reportReducer",
    dataKey: "otherInventoryItemIssueReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Item",
    url: "/other_inventory/item/list",
    action: getAllOtherInventoryItem,
    sliceName: "OtherInventoryItemReducer",
    dataKey: "otherInventoryItemList",
    loaderKey: "isLoading",
    addPageURL: "/other_inventory/item/add",
    editPageURL: "/other_inventory/item/edit",
    deleteAction: deleteOtherInventoryItemById,
  },
  {
    title: "Other Inventory Category",
    url: "/other_inventory/category/list",
    action: getAllOtherInventoryCategory,
    sliceName: "otherInventoryCategoryReducer",
    dataKey: "otherInventoryCategoryList",
    loaderKey: "isLoading",
    addPageURL: "/other_inventory/category/add",
    editPageURL: "/other_inventory/category/edit",
    deleteAction: deleteOtherInventoryCategoryById,
  },
  {
    title: "Size",
    url: "/other_inventory/size/list",
    action: getOtherInventorySize,
    sliceName: "otherInventorySizeReducer",
    dataKey: "otherInventorySizeList",
    loaderKey: "isLoading",
    addPageURL: "/other_inventory/size/add",
    editPageURL: "/other_inventory/size/edit",
    deleteAction: deleteOtherInventorySizeById,
    updateStatusAction: updateOtherInventorySizeStatus,
  },
  {
    title: "Purchase",
    url: "/other_inventory/purchase/list",
    action: getAllOtherInventoryPurchase,
    sliceName: "OtherInventoryPurchaseReducer",
    dataKey: "otherInventoryPurchaseList",
    loaderKey: "isLoading",
    addPageURL: "/other_inventory/purchase/add",
    // editPageURL: "/other_inventory/purchase/edit",
    is_print_req: true,
    printPageURL: "other_inventory/purchase_entry/print",
    cancelAction: cancelOtherInventoryPurchase,
  },
  {
    title: "Item Issue",
    url: "/other_inventory/item_issue/list",
    action: getAllOtherInventoryItemIssue,
    sliceName: "otherInventoryItemIssueReducer",
    dataKey: "otherInventoryItemIssueList",
    loaderKey: "isLoading",
    addPageURL: "/other_inventory/item_issue/add",
    cancelAction: cancelOtherInventoryItemIssue,
  },
  {
    title: "Buy / Sell",
    url: "/mcxrate/buy_sell/list",
    action: getAllBuySell,
    sliceName: "buySellReducer",
    dataKey: "buySellList",
    loaderKey: "isLoading",
    addPageURL: "/mcxrate/buy_sell/add",
  },
  {
    title: "Tag Issue Receipt",
    url: "/inventory/tag/issueReceipt/list",
    action: getTagIssueReceiptList,
    sliceName: "tagReducer",
    dataKey: "tagIssueReceiptList",
    loaderKey: "isLoading",
    addPageURL: "/inventory/tag/issueReceipt/add",
  },
  {
    title: "Lot Issue Receipt",
    url: "/inventory/lot/issueReceipt/list",
    action: getLotIssueReceiptList,
    sliceName: "lotReducer",
    dataKey: "lotIssueReceiptList",
    loaderKey: "isLoading",
    addPageURL: "/inventory/lot/issueReceipt/add",
    is_print_req: true,
    printPageURL: "inventory/lot/issue_receipt/print",
    printType: "page",
  },
  {
    title: "Lot Non Tag Inward",
    url: "/inventory/lot/non_tag_issue/list",
    action: getNonTagInwardList,
    sliceName: "lotReducer",
    dataKey: "nonTagInwardList",
    loaderKey: "isLoading",
    addPageURL: "/inventory/lot/non_tag_issue/add",
  },
  {
    title: "Discount",
    url: "/promotional_management/discount/list",
    action: getAllDiscount,
    sliceName: "promotionManagementDiscountReducer",
    dataKey: "promotionManagementDiscountList",
    loaderKey: "isLoading",
    addPageURL: "/promotional_management/discount/add",
    editPageURL: "/promotional_management/discount/edit",
    deleteAction: deleteDiscountById,
  },
  {
    title: "Coupon",
    url: "/promotional_management/coupon/list",
    action: getAllCoupon,
    sliceName: "promotionManagementCouponReducer",
    dataKey: "promotionManagementCouponList",
    loaderKey: "isLoading",
    addPageURL: "/promotional_management/coupon/add",
    editPageURL: "/promotional_management/coupon/edit",
    deleteAction: deleteCouponById,
  },
  {
    title: "Gift Vouchers",
    url: "/promotional_management/gift_voucher/list",
    action: getAllGiftVoucher,
    sliceName: "promotionManagementGiftVoucherReducer",
    dataKey: "promotionManagementGiftVoucherList",
    loaderKey: "isLoading",
    addPageURL: "/promotional_management/gift_voucher/add",
    editPageURL: "/promotional_management/gift_voucher/edit",
    deleteAction: deleteGiftVoucherById,
  },
  {
    title: "Voucher Issue",
    url: "/promotional_management/voucher_issue/list",
    action: getAllVoucherIssue,
    sliceName: "promotionManagementVoucherIssueReducer",
    dataKey: "promotionManagementVoucherIssueList",
    loaderKey: "isLoading",
    addPageURL: "/promotional_management/voucher_issue/add",
    editPageURL: "/promotional_management/voucher_issue/edit",
    printPageURL: "promotion_management/voucher_issue/print",
    printType: "page",
    is_print_req: true,
  },
  {
    title: "Supplier Payment",
    url: "/purchase/supplier_payment/list",
    action: getSupplierPaymentList,
    sliceName: "purchaseReducer",
    dataKey: "supplierPaymentsLists",
    loaderKey: "isLoading",
    addPageURL: "/purchase/supplier_payment/add",
    editPageURL: "/purchase/supplier_payment/edit",
    printType: "page",
    printPageURL: "purchase/supplier_payment/print",
    detailPrintPageURL: "purchase/supplier_payment/print_thermal",
    is_detail_print_req: true,
    is_print_req: true,
  },

  {
    title: "Loyalty Tiers",
    url: "/loyalty_master/loyalty_tiers/list",
    action: getAllLoyaltyTier,
    deleteAction: deleteLoyaltyTierById,
    // updateStatusAction: updateClientStatus,
    sliceName: "LoyaltyTierReducer",
    dataKey: "loyaltyTierList",
    loaderKey: "isLoading",
    addPageURL: "/loyalty_master/loyalty_tiers/add",
    editPageURL: "/loyalty_master/loyalty_tiers/edit",
  },

  {
    title: "Loyalty Settings",
    url: "/loyalty_master/loyalty_settings/list",
    action: getAllLoyaltySettings,
    deleteAction: deleteLoyaltySettingsById,
    // updateStatusAction: updateClientStatus,
    sliceName: "LoyaltySettingsReducer",
    dataKey: "loyaltySettingsList",
    loaderKey: "isLoading",
    addPageURL: "/loyalty_master/loyalty_settings/add",
    editPageURL: "/loyalty_master/loyalty_settings/edit",
  },

 

  {
    title: "Master Clients",
    url: "/admin/master/masterclient/list",
    action: getAllMasterClients,
    deleteAction: deleteMasterClientsById,
    sliceName: "masterClientReducer",
    dataKey: "masterClientList",
    loaderKey: "isLoading",
    addPageURL: "/admin/master/masterclient/add",
    editPageURL: "/admin/master/masterclient/edit",
  },
  {
    title: "Module Master ",
    url: "/admin/master/module_master/list",
    action: getAllMasterModule,
    deleteAction: deleteMasterModuleById,
    sliceName: "mastermoduleReducer",
    dataKey: "masterModuleList",
    loaderKey: "isLoading",
    addPageURL: "/admin/master/module_master/add",
    editPageURL: "/admin/master/module_master/edit",
  },
  {
    title: "Product Master ",
    url: "/admin/master/product_master/list",
    action: getAllAdminProductMaster,
    deleteAction: deleteAdminProductMasterById,
    sliceName: "adminProductMasterReducer",
    dataKey: "adminProductMasterList",
    loaderKey: "isLoading",
    addPageURL: "/admin/master/product_master/add",
    editPageURL: "/admin/master/product_master/edit",
  },
 
  {
    title: "Liablity",
    url: "/billing/liablity_entry/list",
    action: getLiablityEntry,
    // deleteAction: deleteLoyaltyCustomerById,
    // updateStatusAction: updateClientStatus,
    sliceName: "liablityEntryReducer",
    dataKey: "liablityEntryList",
    loaderKey: "isLoading",
    addPageURL: "/billing/liablity_entry/add",
    editPageURL: "/loyalty_master/loyalty_customer/edit",
    printType: "page",
    printPageURL: "billing/liablity_entry/print",
    is_print_req: true,
  },
  {
    title: "Liablity Payment",
    url: "/billing/liablity_entry_payment/list",
    action: getLiablityEntryPayment,
    // deleteAction: deleteLoyaltyCustomerById,
    // updateStatusAction: updateClientStatus,
    sliceName: "liablityEntryReducer",
    dataKey: "liablityEntryPaymentList",
    loaderKey: "isLoading",
    addPageURL: "/billing/liablity_entry_payment/add",
    printType: "page",
    printPageURL: "billing/liablity_entry_payment/print",
    is_print_req: true,
  },
  {
    title: "Lot Balance Report",
    url: "/reports/lot_balance_report/list",
    action: getLotBalanceReport,
    sliceName: "reportReducer",
    dataKey: "lotBalanceReportList",
    loaderKey: "isLoading",
    updateStatusAction: UpdatelotClose,
    qrPrintAction: printLotQRCode,
    qrPrintType: "lotDetail",
    is_qrprint_req: true,
  },
  {
    title: "Stock Approval Pending",
    url: "/reports/stock_approval_pending/list",
    action: getStockApprovalPendingReport,
    sliceName: "reportReducer",
    dataKey: "stockApprovalPendingReportList",
    loaderKey: "isLoading",
    updateStatusAction: UpdatelotClose,
  },
  {
    title: "Admin Project ",
    url: "/admin/master/projects/list",
    action: getAllProject,
    deleteAction: deleteProjectById,
    sliceName: "projectReducer",
    dataKey: "projectList",
    loaderKey: "isLoading",
    addPageURL: "/admin/master/projects/add",
    editPageURL: "/admin/master/projects/edit",
  },
  {
    title: "Liablity Supplier Payment",
    url: "/reports/liablity_supplier_payment_report/list",
    action: getLiablitySupplierPaymentReport,
    sliceName: "reportReducer",
    dataKey: "liablitySupplierPaymentReportList",
    loaderKey: "isLoading",
    updateStatusAction: UpdatelotClose,
  },
  {
    title: "Admin TASK ",
    url: "/admin/master/task/list",
    action: getAllTask,
    deleteAction: deleteTaskById,
    sliceName: "taskReducer",
    dataKey: "taskList",
    loaderKey: "isLoading",
    addPageURL: "/admin/master/task/add",
    editPageURL: "/admin/master/task/edit",
  },
  {
    title: "Sub Task ",
    url: "/admin/master/sub_task/list",
    action: getAllSubTask,
    deleteAction: deleteSubTaskById,
    sliceName: "subTaskReducer",
    dataKey: "subTaskList",
    loaderKey: "isLoading",
    addPageURL: "/admin/master/sub_task/add",
    editPageURL: "/admin/master/sub_task/edit",
  },
  {
    title: "Purchase Summary",
    url: "/reports/purchase_summary/list",
    action: getPurchasePaymentSummaryReport,
    sliceName: "reportReducer",
    dataKey: "purchasePaymentSummaryList",
    loaderKey: "isLoading",
  },
  {
    title: "Perfomance Invoice ",
    url: "/admin/master/PerformeInvoice/list",
    action: getAllPerformanceInvoice,
    deleteAction: deletePerformanceInvoiceById,
    sliceName: "performanceReducer",
    dataKey: "performanceList",
    loaderKey: "isLoading",
    addPageURL: "/admin/master/PerformeInvoice/add",
    editPageURL: "/admin/master/PerformeInvoice/edit",
  },
  {
    title: "Erp Employee Attendance ",
    url: "/admin/erpemployeeattendance/list",
    action: getAllErpAttendance,
    // deleteAction: deleteErpAttendanceById,
    sliceName: "erpAttendanceReducer",
    dataKey: "erpAttendanceList",
    loaderKey: "isLoading",
    addPageURL: "/admin/erpemployeeattendance/add",
    // editPageURL: "/admin/erpemployeeattendance/edit",
    updateStatusAction: updateErpAttendanceStatus,
  },

  {
    title: "Customer Incentive Sales Log ",
    url: "/reports/incentive/details/list",
    action: customerSalesLog,
    sliceName: "customerSalesLogReducer",
    dataKey: "customerSalesLogReducerList",
    loaderKey: "isLoading",
  },
  {
    title: "Area Wisesales Report",
    url: "/reports/area_wise_sales_report/list",
    action: getareawisesalesreport,
    sliceName: "reportReducer",
    dataKey: "getareawisesalesreportList",
    loaderKey: "isLoading",
  },
];
