import {  getActiveChitsReports, getBranchwise, getChitClosingDetails, getCollectionSummary, getCustomerDetails, getInActiveChits, getMaturedandUnclaimedReports, getPaymentSummaryReports, getRegisterThroughDetails, getschemewise, getUsersJoinedThrough } from "../../../../redux/thunks/crmDashboard";


export const matcherData = [
  {
    title: "Active Chits Report",
    url: "/crm/dashboard/reports/activechits",
    action: getActiveChitsReports,
    sliceName: "crmDashboardReducer",
    dataKey: "activeChitsDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Matured & Unclaimed Report",
    url: "/crm/dashboard/reports/maturedunclaimed",
    action: getMaturedandUnclaimedReports,
    sliceName: "crmDashboardReducer",
    dataKey: "MaturedandUnclaimedDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Payment Report",
    url: "/crm/dashboard/reports/payment",
    action: getPaymentSummaryReports,
    sliceName: "crmDashboardReducer",
    dataKey: "PaymentDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Users Joined Through Report",
    url: "/crm/dashboard/reports/usersjoinedthrough",
    action: getUsersJoinedThrough,
    sliceName: "crmDashboardReducer",
    dataKey: "UsersJoinedThroughDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Scheme Wise Report",
    url: "/crm/dashboard/reports/schemewise",
    action: getschemewise,
    sliceName: "crmDashboardReducer",
    dataKey: "schemewiseDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Branch Wise Report",
    url: "/crm/dashboard/reports/branchwise",
    action: getBranchwise,
    sliceName: "crmDashboardReducer",
    dataKey: "BranchwiseDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Regsiter Through Details Report",
    url: "/crm/dashboard/reports/registerthrough",
    action: getRegisterThroughDetails,
    sliceName: "crmDashboardReducer",
    dataKey: "RegisterThroughDetailsDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Customer Details Report",
    url: "/crm/dashboard/reports/customer_details",
    action: getCustomerDetails,
    sliceName: "crmDashboardReducer",
    dataKey: "CustomerDetailsDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Collection Summary Report",
    url: "/crm/dashboard/reports/collection_summary",
    action: getCollectionSummary,
    sliceName: "crmDashboardReducer",
    dataKey: "CollectionSummaryDashList",
    loaderKey: "isLoading",
  },
  {
    title: "In Active Chits Report",
    url: "/crm/dashboard/reports/inactivechits",
    action: getInActiveChits,
    sliceName: "crmDashboardReducer",
    dataKey: "InActiveChitsDashList",
    loaderKey: "isLoading",
  },
  {
    title: "Chit closing Details Report",
    url: "/crm/dashboard/reports/chitclosing",
    action: getChitClosingDetails,
    sliceName: "crmDashboardReducer",
    dataKey: "ChitClosingDetailsDashList",
    loaderKey: "isLoading",
  },
];
