import {
  getCreditSalesReport,
  getCustomerVistsReports,
  getEstimationReport,
  getLotReport,
  getPurchaseReport,
  getSalesReport,
  getSalesReturnReport,
  getKarigarReport,
  getCustomerOrderReport,
  getStockApprovalReport,
} from "../../../../redux/thunks/retailDashboard";
import {
  fetchTotalOrderDetails,
  fetchTodayRecivedDetails,
  fetchErpTodayDeliveredOrders,
  fetchErpYetToAssignOrders,
  fetchErpTotalDeliveredOrders,
  fetchErpWeekDeliveryOrders,
  fetchErpNextWeekDeliveryOrders,
  fetchErpOverDueOrderSupplier,
  fetchErpCustomerOverDueOrder,
  fetchErpTotalDeliveryReady,
  fetchErpWorkProgress,
} from "../../../../redux/thunks/dashboard";

export const matcherData = [
  {
    title: "Estimation Report",
    url: "/retail/dashboard/reports/estimation",
    action: getEstimationReport,
    sliceName: "retailDashboardReducer",
    dataKey: "estimationDashReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Customer Visit Report",
    url: "/retail/dashboard/reports/customervisits",
    action: getCustomerVistsReports,
    sliceName: "retailDashboardReducer",
    dataKey: "customerVisitsDashReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Sales Report",
    url: "/retail/dashboard/reports/sales",
    action: getSalesReport,
    sliceName: "retailDashboardReducer",
    dataKey: "salesDashReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Sales Return Report",
    url: "/retail/dashboard/reports/salesreturn",
    action: getSalesReturnReport,
    sliceName: "retailDashboardReducer",
    dataKey: "salesReturnDashReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Purchase Report",
    url: "/retail/dashboard/reports/purchase",
    action: getPurchaseReport,
    sliceName: "retailDashboardReducer",
    dataKey: "purchaseDashReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Lot Report",
    url: "/retail/dashboard/reports/lot",
    action: getLotReport,
    sliceName: "retailDashboardReducer",
    dataKey: "lotDashReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Credit Sales Report",
    url: "/retail/dashboard/reports/creditsales",
    action: getCreditSalesReport,
    sliceName: "retailDashboardReducer",
    dataKey: "creditSalesDashReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Karigar Orders Report",
    url: "/retail/dashboard/reports/karigar_order",
    action:   getKarigarReport,
    sliceName: "retailDashboardReducer",
    dataKey: "karigarReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Customer Orders Report",
    url: "/retail/dashboard/reports/customer_order",
    action:   getCustomerOrderReport,
    sliceName: "retailDashboardReducer",
    dataKey: "customerOrderReportList",
    loaderKey: "isLoading",
  },
  {
    title: "Stock Approval Report",
    url: "/retail/dashboard/reports/stock_approval",
    action:   getStockApprovalReport,
    sliceName: "retailDashboardReducer",
    dataKey: "stockApprovalReportList",
    loaderKey: "isLoading",
  },

  {
    title: "Total Order",
    url: "/dashboard/ordermanagement/reports/total_orders",
    action:   fetchTotalOrderDetails,
    sliceName: "dashboardReducer",
    dataKey: "totalOrderDetails",
    loaderKey: "isLoading",
  },


  {
    title: "Today Received",
    url: "/dashboard/ordermanagement/reports/today_received",
    action:   fetchTodayRecivedDetails,
    sliceName: "dashboardReducer",
    dataKey: "todayRecivedDetails",
    loaderKey: "isLoading",
  },

  {
    title: "Today Delivery",
    url: "/dashboard/ordermanagement/reports/today_delivery",
    action:   fetchErpTodayDeliveredOrders,
    sliceName: "dashboardReducer",
    dataKey: "erpTodayDeliveredOrders",
    loaderKey: "isLoading",
  },
  {
    title: "Yet To Assign",
    url: "/dashboard/ordermanagement/reports/yet_to_assign",
    action:   fetchErpYetToAssignOrders,
    sliceName: "dashboardReducer",
    dataKey: "erpYetToAssignOrders",
    loaderKey: "isLoading",
  },

  {
    title: "Total Deliverd",
    url: "/dashboard/ordermanagement/reports/total_deliverd",
    action:   fetchErpTotalDeliveredOrders,
    sliceName: "dashboardReducer",
    dataKey: "erpTotalDeliveredOrders",
    loaderKey: "isLoading",
  },

  {
    title: "This Week Delivery",
    url: "/dashboard/ordermanagement/reports/this_week_delivery",
    action:   fetchErpWeekDeliveryOrders,
    sliceName: "dashboardReducer",
    dataKey: "erpWeekDeliveryOrders",
    loaderKey: "isLoading",
  },
  {
    title: "Next Week Delivery",
    url: "/dashboard/ordermanagement/reports/next_week_delivery",
    action:   fetchErpNextWeekDeliveryOrders,
    sliceName: "dashboardReducer",
    dataKey: "erpNextWeekDeliveryOrders",
    loaderKey: "isLoading",
  },
  {
    title: "Over Due Order Supplier",
    url: "/dashboard/ordermanagement/reports/over_due_order_supplier",
    action:   fetchErpOverDueOrderSupplier,
    sliceName: "dashboardReducer",
    dataKey: "erpOverDueOrderSupplier",
    loaderKey: "isLoading",
  },
  {
    title: "Over Due Order Supplier",
    url: "/dashboard/ordermanagement/reports/customer_over_due_order",
    action:   fetchErpCustomerOverDueOrder,
    sliceName: "dashboardReducer",
    dataKey: "erpCustomerOverDueOrder",
    loaderKey: "isLoading",
  },
  {
    title: "Customer Total Delivery",
    url: "/dashboard/ordermanagement/reports/customer_total_delivery",
    action:   fetchErpTotalDeliveryReady,
    sliceName: "dashboardReducer",
    dataKey: "erpTotalDeliveryReady",
    loaderKey: "isLoading",
  },
  {
    title: "Customer Total Work In Progress",
    url: "/dashboard/ordermanagement/reports/customer_total_work_progress",
    action:   fetchErpWorkProgress,
    sliceName: "dashboardReducer",
    dataKey: "erpWorkProgress",
    loaderKey: "isLoading",
  },
];
