import {
  getClosedAccountReport,
  getCustomerOutstandingReport,
  getModeWiseCollectionReport,
  getSchemeAbstract,
  getSchemeWiseOpeningReport,
  getTagDetailsReport,
  getUnpaidReport,
} from "../../redux/thunks/reports";

export const matcherData = [
  {
    title: "Customer Outstanding Reports",
    url: "/reports/customer_outstanding_report/list",
    action: getCustomerOutstandingReport,
    sliceName: "reportReducer",
    dataKey: "customerOutstandingReportList",
    loaderKey: "isLoading",
    groupingColumns: [],
  },
  {
    title: "Closed Account Report",
    url: "/reports/closed_account_report/list",
    action: getClosedAccountReport,
    sliceName: "reportReducer",
    dataKey: "closedAccountReportList",
    loaderKey: "isLoading",
    groupingColumns: [],
  },
  {
    title: "Mode Wise Collection Report",
    url: "/reports/mode_wise_collection_report/list",
    action: getModeWiseCollectionReport,
    sliceName: "reportReducer",
    dataKey: "modeWiseCollectionReportList",
    loaderKey: "isLoading",
    groupingColumns: [],
  },
  {
    title: "Scheme Abstract Report",
    url: "/reports/schemeabstract/list",
    action: getSchemeAbstract,
    sliceName: "reportReducer",
    dataKey: "schemeAbstractReportList",
    loaderKey: "isLoading",
    groupingColumns: [],
  },
  {
    title: "Scheme Wise Opening Report",
    url: "/reports/scheme_opening_closing/list",
    action: getSchemeWiseOpeningReport,
    sliceName: "reportReducer",
    dataKey: "schemeWiseOpeningReportList",
    loaderKey: "isLoading",
    groupingColumns: [],
  },
  {
    title: "Unpaid Reports",
    url: "/reports/unpaid_report/list",
    action: getUnpaidReport,
    sliceName: "reportReducer",
    dataKey: "unpaidReportList",
    loaderKey: "isLoading",
    groupingColumns: [],
  },
];
