import { combineReducers } from "redux";
import {
  accountHeadReducer,
  areaReducer,
  attributeEntryReducer,
  bankReducer,
  cashOpeningBalanceReducer,
  cityReducer,
  containerReducer,
  counterReducer,
  countryReducer,
  customerProofReducer,
  dayCloseReducer,
  departmentReducer,
  designationReducer,
  employeeTypeReducer,
  financialYearReducer,
  floorReducer,
  karigarReducer,
  metalPurityRateReducer,
  metalRateReducer,
  oldMetalItemReducer,
  otherChargesReducer,
  otherWeightReducer,
  payDeviceReducer,
  professionReducer,
  profileReducer,
  registeredDeviceReducer,
  relationTypeReducer,
  sectionWiseSalesReducer,
  serviceReducer,
  stateReducer,
  stockIssueTypeReducer,
  taxmasterReducer,
  uomReducer,
  weightRangeReducer,
  bankDepositReducer,
  depositMasterReducer,
  incentiveSettingsReducer,
  religionMasterReducer,
  bannerReducer,
  notificationReducer,
  dailyStatusReducer,
  regionReducer,
} from "./retailMasterReducer";
import { coreCompReducer } from "./coreCompReducer";
import { authUserReducer } from "./authUserReducer";
import {
  paymentFormulaReducer,
  schemeAccountReducer,
  schemeClassReducer,
  schemesReducer,
} from "./schemeReducer";
import {
  branchReducer,
  companyReducer,
  menuReducer,
  settingReducer,
} from "./settingsReducer";
import {
  categoryReducer,
  designReducer,
  metalReducer,
  productReducer,
  purityReducer,
  qualityCodeReducer,
  stoneReducer,
  subDesignReducer,
  calTypeReducer,
  taxGroupReducer,
  sectionReducer,
  cutReducer,
  colorReducer,
  shapeReducer,
  clarityReducer,
  qualityReducer,
  subDesignMappingReducer,
  sizeReducer,
  diamondRateMasterReducer,
  reOrderSettingsReducer,
  mcVaSettingsReducer,
  repairDamageMasterReducer,
  categoryPurityRateReducer,
} from "./catalogMasterReducer";
import { reportReducer } from "./reportsReducer";
import { customerReducer } from "./customerReducer";
import { paymentMasterReducer, paymentOptionsreducer } from "./paymentReducer";
import {
  employeeReducer,
  employeeSettingsReducer,
  profileDetailsReducer,
} from "./employeeReducer";
import { dashboardReducer } from "./dashboardReducer";
import {
  lotReducer,
  tagReducer,
  tagBulkEditReducer,
  stockTransferReducer,
  approvalReducer,
  tagAuditReducer,
} from "./inventoryReducer";
import { estReducer } from "./estimationReducer";
import { customerDepositReducer, orderReducer } from "./OrderReducer";
import {
  bankSettlementReducer,
  billingReducer,
  customerSalesLogReducer,
  liablityEntryReducer,
  receiptReducer,
} from "./billingReducer";
import { retailDashboardReducer } from "./retailDashboardReducer";
import {
  purchaseReducer,
  purchaseIssueReceiptReducer,
  purchaseReturnReducer,
} from "./purchaseReducer";
import { metalProcessReducer } from "./metalProcessReducer";
import { importReducer } from "./importExportReducer";
import { crmDashboardReducer } from "./crmDashboardReducer";
import {
  otherInventoryCategoryReducer,
  OtherInventoryItemIssueReducer,
  OtherInventoryItemReducer,
  OtherInventoryPurchaseReducer,
  otherInventorySizeReducer,
} from "./otherInventoryReducer";
import { buySellReducer } from "./mcxReducer";
import { purchaseDashboardReducer } from "./purchaseDashboardReducer";
import {
  promotionManagementCouponReducer,
  promotionManagementDiscountReducer,
  promotionManagementGiftVoucherReducer,
  promotionManagementVoucherIssueReducer,
} from "./promotionManagementReducer";
import { digigoldDashboardReducer } from "./digiGoldDashboardReducer";
import { adminmasterproductreducer, adminProductMasterReducer, clientReducer, masterClientReducer,  mastermoduleReducer} from "./adminMasterReducer";
import { loyaltyCustomerReducer, loyaltyReferralsReducer, LoyaltySettingsReducer, LoyaltyTierReducer, loyaltyTransactionReducer } from "./loyaltyMasterReducer";
import { employeeAttedanceReducer, projectReducer, subTaskReducer, taskReducer , performanceReducer, erpAttendanceReducer} from "./adminProjectReducer";
export * from "./retailMasterReducer";

const allReducers = combineReducers({
  departmentReducer: departmentReducer.reducer,
  designationReducer: designationReducer.reducer,
  coreCompReducer: coreCompReducer.reducer,
  authUserReducer: authUserReducer.reducer,
  areaReducer: areaReducer.reducer,
  bankReducer: bankReducer.reducer,
  financialYearReducer: financialYearReducer.reducer,
  schemeClassReducer: schemeClassReducer.reducer,
  profileReducer: profileReducer.reducer,
  employeeTypeReducer: employeeTypeReducer.reducer,
  companyReducer: companyReducer.reducer,
  countryReducer: countryReducer.reducer,
  stateReducer: stateReducer.reducer,
  cityReducer: cityReducer.reducer,
  metalReducer: metalReducer.reducer,
  purityReducer: purityReducer.reducer,
  paymentFormulaReducer: paymentFormulaReducer.reducer,
  schemesReducer: schemesReducer.reducer,
  reportReducer: reportReducer.reducer,
  customerReducer: customerReducer.reducer,
  metalRateReducer: metalRateReducer.reducer,
  paymentOptionsreducer: paymentOptionsreducer.reducer,
  paymentMasterReducer: paymentMasterReducer.reducer,
  schemeAccountReducer: schemeAccountReducer.reducer,
  categoryReducer: categoryReducer.reducer,
  productReducer: productReducer.reducer,
  designReducer: designReducer.reducer,
  subDesignReducer: subDesignReducer.reducer,
  menuReducer: menuReducer.reducer,
  uomReducer: uomReducer.reducer,
  employeeReducer: employeeReducer.reducer,
  stoneReducer: stoneReducer.reducer,
  qualityCodeReducer: qualityCodeReducer.reducer,
  calTypeReducer: calTypeReducer.reducer,
  branchReducer: branchReducer.reducer,
  taxGroupReducer: taxGroupReducer.reducer,
  metalPurityRateReducer: metalPurityRateReducer.reducer,
  sectionReducer: sectionReducer.reducer,
  dashboardReducer: dashboardReducer.reducer,
  lotReducer: lotReducer.reducer,
  karigarReducer: karigarReducer.reducer,
  taxmasterReducer: taxmasterReducer.reducer,
  cutReducer: cutReducer.reducer,
  colorReducer: colorReducer.reducer,
  shapeReducer: shapeReducer.reducer,
  clarityReducer: clarityReducer.reducer,
  qualityReducer: qualityReducer.reducer,
  subDesignMappingReducer: subDesignMappingReducer.reducer,
  settingReducer: settingReducer.reducer,
  tagReducer: tagReducer.reducer,
  sizeReducer: sizeReducer.reducer,
  profileDetailsReducer: profileDetailsReducer.reducer,
  estReducer: estReducer.reducer,
  attributeEntryReducer: attributeEntryReducer.reducer,
  otherChargesReducer: otherChargesReducer.reducer,
  tagBulkEditReducer: tagBulkEditReducer.reducer,
  orderReducer: orderReducer.reducer,
  dayCloseReducer: dayCloseReducer.reducer,
  diamondRateMasterReducer: diamondRateMasterReducer.reducer,
  payDeviceReducer: payDeviceReducer.reducer,
  stockIssueTypeReducer: stockIssueTypeReducer.reducer,
  billingReducer: billingReducer.reducer,
  stockTransferReducer: stockTransferReducer.reducer,
  approvalReducer: approvalReducer.reducer,
  receiptReducer: receiptReducer.reducer,
  weightRangeReducer: weightRangeReducer.reducer,
  reOrderSettingsReducer: reOrderSettingsReducer.reducer,
  mcVaSettingsReducer: mcVaSettingsReducer.reducer,
  tagAuditReducer: tagAuditReducer.reducer,
  retailDashboardReducer: retailDashboardReducer.reducer,
  employeeSettingsReducer: employeeSettingsReducer.reducer,
  purchaseReducer: purchaseReducer.reducer,
  purchaseReturnReducer: purchaseReturnReducer.reducer,
  purchaseIssueReceiptReducer: purchaseIssueReceiptReducer.reducer,
  metalProcessReducer: metalProcessReducer.reducer,
  floorReducer: floorReducer.reducer,
  counterReducer: counterReducer.reducer,
  registeredDeviceReducer: registeredDeviceReducer.reducer,
  sectionWiseSalesReducer: sectionWiseSalesReducer.reducer,
  professionReducer: professionReducer.reducer,
  relationTypeReducer: relationTypeReducer.reducer,
  bankSettlementReducer: bankSettlementReducer.reducer,
  containerReducer: containerReducer.reducer,
  oldMetalItemReducer: oldMetalItemReducer.reducer,
  otherWeightReducer: otherWeightReducer.reducer,
  accountHeadReducer: accountHeadReducer.reducer,
  cashOpeningBalanceReducer: cashOpeningBalanceReducer.reducer,
  repairDamageMasterReducer: repairDamageMasterReducer.reducer,
  serviceReducer: serviceReducer.reducer,
  customerProofReducer: customerProofReducer.reducer,
  importReducer: importReducer.reducer,
  categoryPurityRateReducer: categoryPurityRateReducer.reducer,
  bankDepositReducer: bankDepositReducer.reducer,
  depositMasterReducer: depositMasterReducer.reducer,
  customerDepositReducer: customerDepositReducer.reducer,
  incentiveSettingsReducer: incentiveSettingsReducer.reducer,
  religionMasterReducer: religionMasterReducer.reducer,
  crmDashboardReducer: crmDashboardReducer.reducer,
  OtherInventoryItemReducer: OtherInventoryItemReducer.reducer,
  otherInventorySizeReducer: otherInventorySizeReducer.reducer,
  otherInventoryItemIssueReducer: OtherInventoryItemIssueReducer.reducer,
  otherInventoryCategoryReducer: otherInventoryCategoryReducer.reducer,
  OtherInventoryPurchaseReducer: OtherInventoryPurchaseReducer.reducer,
  buySellReducer: buySellReducer.reducer,
  purchaseDashboardReducer: purchaseDashboardReducer.reducer,
  promotionManagementDiscountReducer:
    promotionManagementDiscountReducer.reducer,
  promotionManagementCouponReducer: promotionManagementCouponReducer.reducer,
  promotionManagementGiftVoucherReducer:
    promotionManagementGiftVoucherReducer.reducer,
  promotionManagementVoucherIssueReducer:
    promotionManagementVoucherIssueReducer.reducer,
  digigoldDashboardReducer:digigoldDashboardReducer.reducer,
  bannerReducer:bannerReducer.reducer,
    notificationReducer:notificationReducer.reducer,
    dailyStatusReducer:dailyStatusReducer.reducer,
    clientReducer:clientReducer.reducer,
    LoyaltyTierReducer:LoyaltyTierReducer.reducer,
    LoyaltySettingsReducer:LoyaltySettingsReducer.reducer,
    loyaltyCustomerReducer:loyaltyCustomerReducer.reducer,
    loyaltyTransactionReducer:loyaltyTransactionReducer.reducer,
    loyaltyReferralsReducer:loyaltyReferralsReducer.reducer,
    masterClientReducer : masterClientReducer.reducer,
    adminProductMasterReducer : adminProductMasterReducer.reducer,
    mastermoduleReducer: mastermoduleReducer.reducer,
    liablityEntryReducer:liablityEntryReducer.reducer,
    projectReducer:projectReducer.reducer,
    taskReducer:taskReducer.reducer,
    subTaskReducer:subTaskReducer.reducer,
    employeeAttedanceReducer:employeeAttedanceReducer.reducer,
    performanceReducer:performanceReducer.reducer,
    erpAttendanceReducer:erpAttendanceReducer.reducer,
    regionReducer:regionReducer.reducer,
    customerSalesLogReducer:customerSalesLogReducer.reducer,
  });
  
const rootReducer = (state, action) => allReducers(state, action);
export default rootReducer;

// const rootReducer = (asyncReducers) => (state, action) => {
//   const combinedReducer = combineReducers({
//     ...asyncReducers,
//     departmentReducer: departmentReducer.reducer,
//     designationReducer: designationReducer.reducer,
//     coreCompReducer: coreCompReducer.reducer,
//     authUserReducer: authUserReducer.reducer,
//     areaReducer: areaReducer.reducer,
//     bankReducer: bankReducer.reducer,
//     financialYearReducer: financialYearReducer.reducer,
//     schemeClassReducer: schemeClassReducer.reducer,
//     profileReducer: profileReducer.reducer,
//     employeeTypeReducer: employeeTypeReducer.reducer,
//     companyReducer: companyReducer.reducer,
//     countryReducer: countryReducer.reducer,
//     stateReducer: stateReducer.reducer,
//     cityReducer: cityReducer.reducer,
//     metalReducer: metalReducer.reducer,
//     purityReducer: purityReducer.reducer,
//     paymentFormulaReducer: paymentFormulaReducer.reducer,
//     schemesReducer: schemesReducer.reducer,
//     reportReducer: reportReducer.reducer,
//     customerReducer: customerReducer.reducer,
//     metalRateReducer: metalRateReducer.reducer,
//     paymentOptionsreducer: paymentOptionsreducer.reducer,
//     paymentMasterReducer: paymentMasterReducer.reducer,
//     schemeAccountReducer: schemeAccountReducer.reducer,
//     categoryReducer: categoryReducer.reducer,
//     productReducer: productReducer.reducer,
//     designReducer: designReducer.reducer,
//     subDesignReducer: subDesignReducer.reducer,
//     menuReducer: menuReducer.reducer,
//     uomReducer: uomReducer.reducer,
//     employeeReducer: employeeReducer.reducer,
//     stoneReducer: stoneReducer.reducer,
//     qualityCodeReducer: qualityCodeReducer.reducer,
//     calTypeReducer: calTypeReducer.reducer,
//     branchReducer: branchReducer.reducer,
//     taxGroupReducer: taxGroupReducer.reducer,
//     metalPurityRateReducer: metalPurityRateReducer.reducer,
//     sectionReducer: sectionReducer.reducer,
//     dashboardReducer: dashboardReducer.reducer,
//     lotReducer: lotReducer.reducer,
//     karigarReducer: karigarReducer.reducer,
//     taxmasterReducer: taxmasterReducer.reducer,
//     cutReducer: cutReducer.reducer,
//     colorReducer: colorReducer.reducer,
//     shapeReducer: shapeReducer.reducer,
//     clarityReducer: clarityReducer.reducer,
//     qualityReducer: qualityReducer.reducer,
//     subDesignMappingReducer: subDesignMappingReducer.reducer,
//     settingReducer: settingReducer.reducer,
//     tagReducer: tagReducer.reducer,
//     sizeReducer: sizeReducer.reducer,
//     profileDetailsReducer: profileDetailsReducer.reducer,
//     estReducer: estReducer.reducer,
//     attributeEntryReducer: attributeEntryReducer.reducer,
//     otherChargesReducer: otherChargesReducer.reducer,
//     tagBulkEditReducer: tagBulkEditReducer.reducer,
//     orderReducer: orderReducer.reducer,
//     dayCloseReducer: dayCloseReducer.reducer,
//     diamondRateMasterReducer: diamondRateMasterReducer.reducer,
//     payDeviceReducer: payDeviceReducer.reducer,
//     stockIssueTypeReducer: stockIssueTypeReducer.reducer,
//     billingReducer: billingReducer.reducer,
//     stockTransferReducer: stockTransferReducer.reducer,
//     approvalReducer: approvalReducer.reducer,
//     receiptReducer: receiptReducer.reducer,
//     weightRangeReducer: weightRangeReducer.reducer,
//     reOrderSettingsReducer: reOrderSettingsReducer.reducer,
//     mcVaSettingsReducer: mcVaSettingsReducer.reducer,
//     tagAuditReducer: tagAuditReducer.reducer,
//     retailDashboardReducer: retailDashboardReducer.reducer,
//     employeeSettingsReducer: employeeSettingsReducer.reducer,
//     purchaseReducer: purchaseReducer.reducer,
//     purchaseReturnReducer: purchaseReturnReducer.reducer,
//     purchaseIssueReceiptReducer: purchaseIssueReceiptReducer.reducer,
//     metalProcessReducer: metalProcessReducer.reducer,
//     floorReducer: floorReducer.reducer,
//     counterReducer: counterReducer.reducer,
//     registeredDeviceReducer: registeredDeviceReducer.reducer,
//     sectionWiseSalesReducer: sectionWiseSalesReducer.reducer,
//     professionReducer: professionReducer.reducer,
//     relationTypeReducer: relationTypeReducer.reducer,
//     bankSettlementReducer: bankSettlementReducer.reducer,
//     containerReducer: containerReducer.reducer,
//     oldMetalItemReducer: oldMetalItemReducer.reducer,
//     otherWeightReducer: otherWeightReducer.reducer,
//     accountHeadReducer: accountHeadReducer.reducer,
//     cashOpeningBalanceReducer: cashOpeningBalanceReducer.reducer,
//     repairDamageMasterReducer: repairDamageMasterReducer.reducer,
//     serviceReducer: serviceReducer.reducer,
//     customerProofReducer: customerProofReducer.reducer,
//     importReducer: importReducer.reducer,
//     categoryPurityRateReducer: categoryPurityRateReducer.reducer,
//     bankDepositReducer: bankDepositReducer.reducer,
//     depositMasterReducer: depositMasterReducer.reducer,
//     customerDepositReducer: customerDepositReducer.reducer,
//     incentiveSettingsReducer: incentiveSettingsReducer.reducer,
//     religionMasterReducer: religionMasterReducer.reducer,
//     crmDashboardReducer: crmDashboardReducer.reducer,
//     OtherInventoryItemReducer: OtherInventoryItemReducer.reducer,
//     otherInventorySizeReducer: otherInventorySizeReducer.reducer,
//     otherInventoryItemIssueReducer: OtherInventoryItemIssueReducer.reducer,
//     otherInventoryCategoryReducer: otherInventoryCategoryReducer.reducer,
//     OtherInventoryPurchaseReducer: OtherInventoryPurchaseReducer.reducer,
//     buySellReducer: buySellReducer.reducer,
//     purchaseDashboardReducer: purchaseDashboardReducer.reducer,
//     promotionManagementDiscountReducer:
//       promotionManagementDiscountReducer.reducer,
//     promotionManagementCouponReducer: promotionManagementCouponReducer.reducer,
//     promotionManagementGiftVoucherReducer:
//       promotionManagementGiftVoucherReducer.reducer,
//     promotionManagementVoucherIssueReducer:
//       promotionManagementVoucherIssueReducer.reducer,
//     digigoldDashboardReducer:digigoldDashboardReducer.reducer,
//     bannerReducer:bannerReducer.reducer,
//     notificationReducer:notificationReducer.reducer,
//     dailyStatusReducer:dailyStatusReducer.reducer,
//     clientReducer:clientReducer.reducer,
//     LoyaltyTierReducer:LoyaltyTierReducer.reducer,
//     LoyaltySettingsReducer:LoyaltySettingsReducer.reducer,
//     loyaltyCustomerReducer:loyaltyCustomerReducer.reducer,
//     loyaltyTransactionReducer:loyaltyTransactionReducer.reducer,
//     loyaltyReferralsReducer:loyaltyReferralsReducer.reducer,
//     masterClientReducer : masterClientReducer.reducer,
//     adminProductMasterReducer : adminProductMasterReducer.reducer,
//     mastermoduleReducer: mastermoduleReducer.reducer,
//     liablityEntryReducer:liablityEntryReducer.reducer,
//   });
//   return combinedReducer(state, action);
// };

// export default rootReducer;
