import { Auth } from "../configs";

const api = {
  scheme_reports: {
    createMetal: (content) => Auth.post("/catalogmasters/metal/", content),
    getSchemeAbstract: (content) => Auth.post("/reports/collection_report/", content),
    getMonthWiseSchemeJoin: (content) => Auth.post("/reports/month_wise_scheme_join/", content),
    getMonthWiseSchemeCollection: (content) => Auth.post("/reports/month_wise_scheme_collection/", content),
    getChitCustomerReport: (content) => Auth.post("/reports/chit_customer_report/", content),
    getUnpaidReport: (content) => Auth.post("/reports/unpaid_report/", content),
    getCustomerOutstandingReport: (content) => Auth.post("/reports/customer_outstanding_report/", content),
    getModeWiseCollectionReport: (content) => Auth.post("/reports/mode_wise_collection/", content),
    getClosedAccountReport: (content) => Auth.post("/reports/closed_account_report/", content),
    getSchemeWiseOpeningReport: (content) => Auth.post("/reports/scheme_wise_opening/", content),
  },
  retail_report: {
    getEmployeeIncentiveReport: (page, records, content,search) => Auth.post(`/reports/incentive_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getEstimateReport: (page, records, content,search) => Auth.post(`/reports/estimate_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getAbove2LakhsBillsReport: (page, records, content,search) => Auth.post(`/reports/above_2L_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getStockInAndOutReport: (page, records, content, search) => Auth.post(`/reports/stock_in_and_out/?page=${page}&records=${records}&searchText=${search}`, content),
    getStockReport: (page, records, content, search) => Auth.post(`/reports/available_stock/?page=${page}&records=${records}&search=${search}`, content),
    getStockTrasferReport: (page, records, content, search) => Auth.post(`/reports/stock_transfer/?page=${page}&records=${records}&searchText=${search}`, content),
    getSalesReport: (page, records, content, search) => Auth.post(`/reports/sales_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getPurchaseReport: (page, records, content, search) => Auth.post(`/reports/purchase_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getCashAbstractReport: (page, records, content, search) => Auth.post(`/reports/cash_abstract_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getStockAuditReport: (page, records, content, search) => Auth.post(`/reports/stock_audit_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getStockAuditDetailReport: (page, records, content, search) => Auth.post(`/reports/stock_audit_detail_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getStockAuditDetailReportPrint: (page, records, content, search) => Auth.post(`/reports/stock_audit_detail_report/print/?page=${page}&records=${records}&searchText=${search}`, content),
    getB2bReport: (page, records, content, search) => Auth.post(`/reports/b2b_sales_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getAdvanceReport: (page, records, content, search) => Auth.post(`/reports/advance_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getCreditInvoiceReportReport: (page, records, content, search) => Auth.post(`/reports/credit_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getCreditCollectionReportReport: (page, records, content, search) => Auth.post(`/reports/credit_collection_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getReorderReportReport: (page, records, content, search) => Auth.post(`/reports/sales_prediction/?page=${page}&records=${records}&searchText=${search}`, content),
    getAdvanceAdjReport: (page, records, content, search) => Auth.post(`/reports/advance_adj/?page=${page}&records=${records}&searchText=${search}`, content),
    getChitAdjReport: (page, records, content, search) => Auth.post(`/reports/chit_adj/?page=${page}&records=${records}&searchText=${search}`, content),
    getAdvanceRefundReport: (page, records, content, search) => Auth.post(`/reports/advance_refund/?page=${page}&records=${records}&searchText=${search}`, content),
    getSalesReturnReport: (page, records, content, search) => Auth.post(`/reports/sales_return_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getCreditPendingReport: (page, records, content, search) => Auth.post(`/reports/credit_pending_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getPettyCashReport: (page, records, content, search) => Auth.post(`/reports/petty_cash_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getEmployeeSalesReport: (page, records, content, search) => Auth.post(`/reports/emp_sales_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getCreditIssuePendingReport: (page, records, content, search) => Auth.post(`/reports/credit_issue_pending_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getReOrderAvailabilityReport: (page, records, content, search) => Auth.post(`/reports/re_order_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getPartlySalesReport: (page, records, content, search) => Auth.post(`/reports/partly_sales_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getSupplierWiseSalesReport: (page, records, content, search) => Auth.post(`/reports/karigar_wise_sales_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getTagWiseProfitReport: (page, records, content, search) => Auth.post(`/reports/tag_wise_profit_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getCancelBillsReport: (page, records, content, search) => Auth.post(`/reports/cancel_bills_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getDiscountBillsReport: (page, records, content, search) => Auth.post(`/reports/discount_bill_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getPanBillsReport: (page, records, content, search) => Auth.post(`/reports/pan_bill_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getBillWiseTransactionReport: (page, records, content, search) => Auth.post(`/reports/billwise_transaction_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getSalesAndSalesReturnGSTReport: (page, records, content, search) => Auth.post(`/reports/sales_and_return_gst_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getSalesTargetReport: (page, records, content, search) => Auth.post(`/reports/sales_target_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getJewelNotDeliveredReport: (page, records, content, search) => Auth.post(`/reports/jewel_not_delivered_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getCreditTobeReport: (page, records, content, search) => Auth.post(`/reports/credit_tobe_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getDailyAbstractReport: (page, records, content, search) => Auth.post(`/reports/category_wise_abstract_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getMetalProcessReport: (page, records, content, search) => Auth.post(`/reports/metal_process_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getOtherMetalStockInAndOutReport: (page, records, content, search) => Auth.post(`/reports/other_metal_stock_in_and_out/?page=${page}&records=${records}&searchText=${search}`, content),
    getCashBookReport: (page, records, content, search) => Auth.post(`/reports/cash_book/?page=${page}&records=${records}&searchText=${search}`, content),
    getSupplierLedgerReport: (content) => Auth.post(`/reports/supplier_ledger/`, content),
    getEdaSalesReport: (page, records, content, search) => Auth.post(`/reports/sale_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getEdaPurchaseReport: (page, records, content, search) => Auth.post(`/reports/purchases_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getPurchaseReturnReport: (page, records, content, search) => Auth.post(`/reports/purchase_return_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getTagDetailsReport: (page, records, content, search) => Auth.post(`/reports/tag_details_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getOtherMetalProfitLossReport: (page, records, content, search) => Auth.post(`/reports/other_metal_profit_loss_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getBankStatementReport: (page, records, content, search) => Auth.post(`/reports/bank_statement_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getSuppliersLedgerReport: (page, records, content, search) => Auth.post(`/reports/suppliers_ledger/?page=${page}&records=${records}&searchText=${search}`, content),
    getWeightRangeWiseSaleReport: (page, records, content, search) => Auth.post(`/reports/sales_based_on_Weight_range_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getPaymentDevicesWiseReport: (page, records, content, search) => Auth.post(`/reports/payment_devices_wise_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getStockAnalysisReport: (page, records, content, search) => Auth.post(`/reports/stock_analysis/?page=${page}&records=${records}&searchText=${search}`, content),
    getSupplierCatalogReport: (page, records, content, search) => Auth.post(`/reports/supplier_catalog_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getLotReport: (page, records, content, search) => Auth.post(`/reports/lot_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getLotBalanceReport: (page, records, content, search) => Auth.post(`/reports/lot_balance_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getStockInwardReport: (page, records, content, search) => Auth.post(`/reports/stock_inward_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getDailyCashBookReport: (content) => Auth.post("/reports/cash_book_report/", content),
    getBillViewReport: (content) => Auth.post("/reports/bill_view_report/", content),
    getMonthWiseSalesReport: (content) => Auth.post("/reports/month_wise_sales/", content),
    getMonthWisePurchaseEntryReport: (content) => Auth.post("/reports/month_wise_purchase_entry/", content),
    getCustomerJewelNotDeliveredReport: (content) => Auth.post("/billing/customer_jewel_not_delivered/", content),
    getOtherInventoryItemLogReport: (content) => Auth.post("/other_inventory/log_report/", content),
    getOtherInventoryItemPurchaseReport: (content) => Auth.post("/other_inventory/purchase_report/", content),
    getOtherInventoryItemIssueReport: (content) => Auth.post("/other_inventory/issue_report/", content),
    getVoucherIssueReport: (content) => Auth.post("/promotion_management/gift_voucher_issue_report/", content),
    getDigiGoldReport: (content) => Auth.post("/reports/digi_gold/", content),
    getAccountWiseDigiGoldReport: (content) => Auth.post("/reports/account_wise_digi_gold/", content),
    getStockApprovalPendingReport: (page, records, content, search) => Auth.post(`/reports/stock_approval_pending/?page=${page}&records=${records}&searchText=${search}`, content),
    getLiablitySupplierPaymentReport: (page, records, content, search) => Auth.post(`/reports/liablity_supplier_payment_report/?page=${page}&records=${records}&searchText=${search}`, content),
    getPurchasePaymentSummaryReport: (page, records, content, search) => Auth.post(`/reports/purchase_report_summary/?page=${page}&records=${records}&searchText=${search}`, content),
    getareawisesalesreport: (page, records, content, search) => Auth.post(`/reports/area_wise_sales_report/?page=${page}&records=${records}&searchText=${search}`, content),
  },
  search_history: {
    getSearchCustomerHistory: (content) => Auth.post(`/reports/search_customer/`, content),
    getSearchSupplierHistory: (content) => Auth.post(`/reports/search_supplier/`, content),
    getSearchTagHistory: (content) => Auth.post(`/reports/search_tag/`, content),
  }
};
const reportsAPI = { ...api };

export default reportsAPI;
